In [1]:
pip install librosa soundfile numpy

Collecting librosa
  Downloading librosa-0.11.0-py3-none-any.whl.metadata (8.7 kB)
Collecting soundfile
  Downloading soundfile-0.13.1-py2.py3-none-win_amd64.whl.metadata (16 kB)
Requirement already satisfied: numpy in c:\users\dell\appdata\roaming\python\python312\site-packages (2.1.3)
Collecting audioread>=2.1.9 (from librosa)
  Downloading audioread-3.0.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: numba>=0.51.0 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (0.59.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (1.16.1)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (1.7.1)
Requirement already satisfied: joblib>=1.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (1.5.1)
Requirement already satisfied: decorator>=4.3.0 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (5.1.1)
Collecting pooch>=1.1 (from librosa)
  Downloading pooch-1.8.2-py3-none-any.whl.metadata (10 kB)
Collecting soxr>=0.3.2 (from librosa)
  Downloading soxr-1.0.0-cp312-abi3-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: typing_extensions>=4.1.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (4.14.1)
Requirement already satisfied: lazy_loader>=0.1 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (0.4)
Requirement already satisfied: msgpack>=1.0 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (1.0.3)
Requirement already satisfied: cffi>=1.0 in c:\users\dell\anaconda3\lib\site-packages (from soundfile) (1.16.0)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.0->soundfile) (2.21)
Requirement already satisfied: packaging in c:\users\dell\appdata\roaming\python\python312\site-packages (from lazy_loader>=0.1->librosa) (25.0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in c:\users\dell\anaconda3\lib\site-packages (from numba>=0.51.0->librosa) (0.42.0)
Collecting numpy
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: platformdirs>=2.5.0 in c:\users\dell\anaconda3\lib\site-packages (from pooch>=1.1->librosa) (3.10.0)
Requirement already satisfied: requests>=2.19.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pooch>=1.1->librosa) (2.32.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\appdata\roaming\python\python312\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\roaming\python\python312\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\appdata\roaming\python\python312\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2025.7.14)
Downloading librosa-0.11.0-py3-none-any.whl (260 kB)
   ---------------------------------------- 0.0/260.7 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/260.7 kB 435.7 kB/s eta 0:00:01
   ------ -------------------------------- 41.0/260.7 kB 495.5 kB/s eta 0:00:01
   ---------------- --------------------- 112.6/260.7 kB 939.4 kB/s eta 0:00:01
   ------------------------- ------------ 174.1/260.7 kB 876.1 kB/s eta 0:00:01
   ---------------------------------------  256.0/260.7 kB 1.1 MB/s eta 0:00:01
   -------------------------------------- 260.7/260.7 kB 945.3 kB/s eta 0:00:00
Downloading soundfile-0.13.1-py2.py3-none-win_amd64.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.0 MB 2.0 MB/s eta 0:00:01
   ---- ----------------------------------- 0.1/1.0 MB 2.4 MB/s eta 0:00:01
   ------ --------------------------------- 0.2/1.0 MB 1.8 MB/s eta 0:00:01
   ------ --------------------------------- 0.2/1.0 MB 1.8 MB/s eta 0:00:01
   -------- ------------------------------- 0.2/1.0 MB 1.1 MB/s eta 0:00:01
   ------------------ --------------------- 0.5/1.0 MB 1.9 MB/s eta 0:00:01
   ---------------------- ----------------- 0.6/1.0 MB 2.0 MB/s eta 0:00:01
   -------------------------- ------------- 0.7/1.0 MB 2.0 MB/s eta 0:00:01
   ------------------------------- -------- 0.8/1.0 MB 1.9 MB/s eta 0:00:01
   --------------------------------- ------ 0.9/1.0 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 1.0/1.0 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 1.0/1.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 1.0/1.0 MB 1.7 MB/s eta 0:00:00
Downloading audioread-3.0.1-py3-none-any.whl (23 kB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Downloading pooch-1.8.2-py3-none-any.whl (64 kB)
   ---------------------------------------- 0.0/64.6 kB ? eta -:--:--
   -------------------------------------- - 61.4/64.6 kB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 64.6/64.6 kB 876.4 kB/s eta 0:00:00
Downloading soxr-1.0.0-cp312-abi3-win_amd64.whl (172 kB)
   ---------------------------------------- 0.0/172.1 kB ? eta -:--:--
   ---------------- ----------------------- 71.7/172.1 kB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 163.8/172.1 kB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 172.1/172.1 kB 1.7 MB/s eta 0:00:00
Installing collected packages: numpy, audioread, soxr, soundfile, pooch, librosa
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3
Successfully installed audioread-3.0.1 librosa-0.11.0 numpy-1.26.4 pooch-1.8.2 soundfile-0.13.1 soxr-1.0.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping C:\Users\DELL\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\DELL\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\~-mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
category-encoders 2.7.0 requires scikit-learn<1.6.0,>=1.0.0, but you have scikit-learn 1.7.1 which is incompatible.
pycaret 3.3.2 requires joblib<1.4,>=1.2.0, but you have joblib 1.5.1 which is incompatible.
pycaret 3.3.2 requires matplotlib<3.8.0, but you have matplotlib 3.10.5 which is incompatible.
pycaret 3.3.2 requires pandas<2.2.0, but you have pandas 2.3.1 which is incompatible.
pycaret 3.3.2 requires scipy<=1.11.4,>=1.6.1, but you have scipy 1.16.1 which is incompatible.
sktime 0.26.0 requires pandas<2.2.0,>=1.1, but you have pandas 2.3.1 which is incompatible.
sktime 0.26.0 requires scikit-learn<1.5.0,>=0.24, but you have scikit-learn 1.7.1 which is incompatible.

In [21]:
import librosa
import numpy as np

def extract_audio_features(audio_path):
    y, sr = librosa.load(audio_path, sr=None)
    
    # Tempo (speech rate تقريبًا)
    tempo, _ = librosa.beat.beat_track(y=y, sr=sr)
    
    # Energy (Root Mean Square)
    rms = np.mean(librosa.feature.rms(y=y))
    
    # Pitch (frequency)
    pitches, magnitudes = librosa.piptrack(y=y, sr=sr)
    pitch_values = pitches[magnitudes > np.median(magnitudes)]
    pitch_mean = np.mean(pitch_values)
    pitch_std = np.std(pitch_values)
    
    # نعمل normalization بسيطة
    speech_rate_score = min(1.0, tempo / 250)
    energy_score = min(1.0, rms * 50)
    confidence_score = min(1.0, (energy_score + speech_rate_score) / 2)

    return {
        "speech_rate_score": round(float(speech_rate_score), 3),
        "energy_score": round(float(energy_score), 3),
        "confidence_score": round(float(confidence_score), 3),
        "pitch_mean": round(float(pitch_mean), 3),
        "pitch_std": round(float(pitch_std), 3)
    }

In [11]:
!pip install moviepy

Collecting moviepy
  Downloading moviepy-2.2.1-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: decorator<6.0,>=4.0.2 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (5.1.1)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (2.33.1)
Collecting imageio_ffmpeg>=0.2.0 (from moviepy)
  Downloading imageio_ffmpeg-0.6.0-py3-none-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: numpy>=1.25.0 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (1.26.4)
Collecting proglog<=1.0.0 (from moviepy)
  Downloading proglog-0.1.12-py3-none-any.whl.metadata (794 bytes)
Requirement already satisfied: python-dotenv>=0.10 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (0.21.0)
Requirement already satisfied: pillow<12.0,>=9.2.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from moviepy) (11.3.0)
Requirement already satisfied: tqdm in c:\users\dell\appdata\roaming\python\python312\site-packages (from proglog<=1.0.0->moviepy) (4.67.1)
Requirement already satisfied: colorama in c:\users\dell\appdata\roaming\python\python312\site-packages (from tqdm->proglog<=1.0.0->moviepy) (0.4.6)
Downloading moviepy-2.2.1-py3-none-any.whl (129 kB)
   ---------------------------------------- 0.0/129.9 kB ? eta -:--:--
   --- ------------------------------------ 10.2/129.9 kB ? eta -:--:--
   ------ -------------------------------- 20.5/129.9 kB 320.0 kB/s eta 0:00:01
   --------- ----------------------------- 30.7/129.9 kB 262.6 kB/s eta 0:00:01
   ------------ -------------------------- 41.0/129.9 kB 245.8 kB/s eta 0:00:01
   -------------------------------- ----- 112.6/129.9 kB 544.7 kB/s eta 0:00:01
   -------------------------------------- 129.9/129.9 kB 478.5 kB/s eta 0:00:00
Downloading imageio_ffmpeg-0.6.0-py3-none-win_amd64.whl (31.2 MB)
   ---------------------------------------- 0.0/31.2 MB ? eta -:--:--
   ---------------------------------------- 0.1/31.2 MB 1.7 MB/s eta 0:00:19
   ---------------------------------------- 0.1/31.2 MB 1.3 MB/s eta 0:00:24
   ---------------------------------------- 0.2/31.2 MB 1.7 MB/s eta 0:00:19
   ---------------------------------------- 0.3/31.2 MB 1.7 MB/s eta 0:00:18
    --------------------------------------- 0.4/31.2 MB 1.8 MB/s eta 0:00:17
    --------------------------------------- 0.5/31.2 MB 1.7 MB/s eta 0:00:18
    --------------------------------------- 0.5/31.2 MB 1.7 MB/s eta 0:00:18
    --------------------------------------- 0.6/31.2 MB 1.4 MB/s eta 0:00:22
    --------------------------------------- 0.7/31.2 MB 1.6 MB/s eta 0:00:19
   - -------------------------------------- 1.0/31.2 MB 2.0 MB/s eta 0:00:16
   - -------------------------------------- 1.1/31.2 MB 2.0 MB/s eta 0:00:16
   - -------------------------------------- 1.2/31.2 MB 2.0 MB/s eta 0:00:16
   - -------------------------------------- 1.3/31.2 MB 2.0 MB/s eta 0:00:16
   - -------------------------------------- 1.4/31.2 MB 2.0 MB/s eta 0:00:15
   - -------------------------------------- 1.5/31.2 MB 2.0 MB/s eta 0:00:15
   -- ------------------------------------- 1.6/31.2 MB 2.0 MB/s eta 0:00:15
   -- ------------------------------------- 1.7/31.2 MB 2.0 MB/s eta 0:00:15
   -- ------------------------------------- 1.8/31.2 MB 2.0 MB/s eta 0:00:15
   -- ------------------------------------- 1.9/31.2 MB 2.0 MB/s eta 0:00:15
   -- ------------------------------------- 2.0/31.2 MB 2.0 MB/s eta 0:00:15
   -- ------------------------------------- 2.1/31.2 MB 2.0 MB/s eta 0:00:15
   -- ------------------------------------- 2.2/31.2 MB 2.0 MB/s eta 0:00:15
   -- ------------------------------------- 2.3/31.2 MB 2.0 MB/s eta 0:00:15
   --- ------------------------------------ 2.4/31.2 MB 2.0 MB/s eta 0:00:15
   --- ------------------------------------ 2.5/31.2 MB 2.0 MB/s eta 0:00:15
   --- ------------------------------------ 2.6/31.2 MB 2.0 MB/s eta 0:00:14
   --- ------------------------------------ 2.7/31.2 MB 2.1 MB/s eta 0:00:14
   --- ------------------------------------ 2.8/31.2 MB 2.0 MB/s eta 0:00:14
   --- ------------------------------------ 2.9/31.2 MB 2.0 MB/s eta 0:00:14
   --- ------------------------------------ 2.9/31.2 MB 2.0 MB/s eta 0:00:14
   --- ------------------------------------ 2.9/31.2 MB 2.0 MB/s eta 0:00:14
   --- ------------------------------------ 3.1/31.2 MB 2.0 MB/s eta 0:00:15
   ---- ----------------------------------- 3.3/31.2 MB 2.0 MB/s eta 0:00:14
   ---- ----------------------------------- 3.5/31.2 MB 2.0 MB/s eta 0:00:14
   ---- ----------------------------------- 3.5/31.2 MB 2.0 MB/s eta 0:00:14
   ---- ----------------------------------- 3.6/31.2 MB 2.0 MB/s eta 0:00:14
   ---- ----------------------------------- 3.7/31.2 MB 2.1 MB/s eta 0:00:14
   ---- ----------------------------------- 3.9/31.2 MB 2.1 MB/s eta 0:00:14
   ----- ---------------------------------- 4.0/31.2 MB 2.1 MB/s eta 0:00:14
   ----- ---------------------------------- 4.1/31.2 MB 2.0 MB/s eta 0:00:14
   ----- ---------------------------------- 4.2/31.2 MB 2.1 MB/s eta 0:00:14
   ----- ---------------------------------- 4.3/31.2 MB 2.1 MB/s eta 0:00:14
   ----- ---------------------------------- 4.4/31.2 MB 2.1 MB/s eta 0:00:14
   ----- ---------------------------------- 4.5/31.2 MB 2.1 MB/s eta 0:00:13
   ----- ---------------------------------- 4.6/31.2 MB 2.1 MB/s eta 0:00:13
   ------ --------------------------------- 4.7/31.2 MB 2.1 MB/s eta 0:00:13
   ------ --------------------------------- 4.8/31.2 MB 2.1 MB/s eta 0:00:13
   ------ --------------------------------- 4.9/31.2 MB 2.1 MB/s eta 0:00:13
   ------ --------------------------------- 5.0/31.2 MB 2.1 MB/s eta 0:00:13
   ------ --------------------------------- 5.1/31.2 MB 2.1 MB/s eta 0:00:13
   ------ --------------------------------- 5.2/31.2 MB 2.1 MB/s eta 0:00:13
   ------ --------------------------------- 5.3/31.2 MB 2.1 MB/s eta 0:00:13
   ------ --------------------------------- 5.4/31.2 MB 2.1 MB/s eta 0:00:13
   ------- -------------------------------- 5.5/31.2 MB 2.1 MB/s eta 0:00:13
   ------- -------------------------------- 5.6/31.2 MB 2.1 MB/s eta 0:00:13
   ------- -------------------------------- 5.7/31.2 MB 2.1 MB/s eta 0:00:13
   ------- -------------------------------- 5.8/31.2 MB 2.1 MB/s eta 0:00:13
   ------- -------------------------------- 5.9/31.2 MB 2.1 MB/s eta 0:00:13
   ------- -------------------------------- 6.0/31.2 MB 2.1 MB/s eta 0:00:13
   ------- -------------------------------- 6.1/31.2 MB 2.1 MB/s eta 0:00:13
   ------- -------------------------------- 6.2/31.2 MB 2.1 MB/s eta 0:00:13
   -------- ------------------------------- 6.3/31.2 MB 2.1 MB/s eta 0:00:13
   -------- ------------------------------- 6.4/31.2 MB 2.1 MB/s eta 0:00:13
   -------- ------------------------------- 6.5/31.2 MB 2.1 MB/s eta 0:00:13
   -------- ------------------------------- 6.6/31.2 MB 2.1 MB/s eta 0:00:13
   -------- ------------------------------- 6.7/31.2 MB 2.1 MB/s eta 0:00:12
   -------- ------------------------------- 6.8/31.2 MB 2.0 MB/s eta 0:00:12
   -------- ------------------------------- 6.9/31.2 MB 2.1 MB/s eta 0:00:12
   -------- ------------------------------- 7.0/31.2 MB 2.1 MB/s eta 0:00:12
   --------- ------------------------------ 7.1/31.2 MB 2.1 MB/s eta 0:00:12
   --------- ------------------------------ 7.2/31.2 MB 2.1 MB/s eta 0:00:12
   --------- ------------------------------ 7.3/31.2 MB 2.1 MB/s eta 0:00:12
   --------- ------------------------------ 7.4/31.2 MB 2.1 MB/s eta 0:00:12
   --------- ------------------------------ 7.5/31.2 MB 2.1 MB/s eta 0:00:12
   --------- ------------------------------ 7.5/31.2 MB 2.1 MB/s eta 0:00:12
   --------- ------------------------------ 7.7/31.2 MB 2.1 MB/s eta 0:00:12
   --------- ------------------------------ 7.8/31.2 MB 2.1 MB/s eta 0:00:12
   ---------- ----------------------------- 7.9/31.2 MB 2.1 MB/s eta 0:00:12
   ---------- ----------------------------- 8.0/31.2 MB 2.1 MB/s eta 0:00:12
   ---------- ----------------------------- 8.1/31.2 MB 2.1 MB/s eta 0:00:12
   ---------- ----------------------------- 8.2/31.2 MB 2.1 MB/s eta 0:00:12
   ---------- ----------------------------- 8.3/31.2 MB 2.1 MB/s eta 0:00:12
   ---------- ----------------------------- 8.4/31.2 MB 2.1 MB/s eta 0:00:12
   ---------- ----------------------------- 8.5/31.2 MB 2.1 MB/s eta 0:00:12
   ---------- ----------------------------- 8.6/31.2 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 8.7/31.2 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 8.8/31.2 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 8.9/31.2 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 9.0/31.2 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 9.1/31.2 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 9.2/31.2 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 9.3/31.2 MB 2.1 MB/s eta 0:00:11
   ----------- ---------------------------- 9.4/31.2 MB 2.1 MB/s eta 0:00:11
   ------------ --------------------------- 9.5/31.2 MB 2.1 MB/s eta 0:00:11
   ------------ --------------------------- 9.6/31.2 MB 2.1 MB/s eta 0:00:11
   ------------ --------------------------- 9.7/31.2 MB 2.1 MB/s eta 0:00:11
   ------------ --------------------------- 9.8/31.2 MB 2.1 MB/s eta 0:00:11
   ------------ --------------------------- 9.9/31.2 MB 2.1 MB/s eta 0:00:11
   ------------ --------------------------- 10.0/31.2 MB 2.1 MB/s eta 0:00:11
   ------------ --------------------------- 10.1/31.2 MB 2.1 MB/s eta 0:00:11
   ------------- -------------------------- 10.2/31.2 MB 2.1 MB/s eta 0:00:11
   ------------- -------------------------- 10.3/31.2 MB 2.1 MB/s eta 0:00:11
   ------------- -------------------------- 10.4/31.2 MB 2.1 MB/s eta 0:00:11
   ------------- -------------------------- 10.5/31.2 MB 2.1 MB/s eta 0:00:11
   ------------- -------------------------- 10.6/31.2 MB 2.1 MB/s eta 0:00:10
   ------------- -------------------------- 10.7/31.2 MB 2.1 MB/s eta 0:00:10
   ------------- -------------------------- 10.8/31.2 MB 2.1 MB/s eta 0:00:10
   -------------- ------------------------- 10.9/31.2 MB 2.1 MB/s eta 0:00:10
   -------------- ------------------------- 11.0/31.2 MB 2.1 MB/s eta 0:00:10
   -------------- ------------------------- 11.1/31.2 MB 2.1 MB/s eta 0:00:10
   -------------- ------------------------- 11.2/31.2 MB 2.1 MB/s eta 0:00:10
   -------------- ------------------------- 11.3/31.2 MB 2.1 MB/s eta 0:00:10
   -------------- ------------------------- 11.4/31.2 MB 2.1 MB/s eta 0:00:10
   -------------- ------------------------- 11.5/31.2 MB 2.1 MB/s eta 0:00:10
   -------------- ------------------------- 11.6/31.2 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 11.7/31.2 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 11.8/31.2 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 11.9/31.2 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 12.0/31.2 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 12.1/31.2 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 12.2/31.2 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 12.3/31.2 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 12.4/31.2 MB 2.1 MB/s eta 0:00:10
   ---------------- ----------------------- 12.5/31.2 MB 2.1 MB/s eta 0:00:10
   ---------------- ----------------------- 12.6/31.2 MB 2.1 MB/s eta 0:00:09
   ---------------- ----------------------- 12.7/31.2 MB 2.1 MB/s eta 0:00:09
   ---------------- ----------------------- 12.8/31.2 MB 2.1 MB/s eta 0:00:09
   ---------------- ----------------------- 12.9/31.2 MB 2.1 MB/s eta 0:00:09
   ---------------- ----------------------- 13.0/31.2 MB 2.1 MB/s eta 0:00:09
   ---------------- ----------------------- 13.1/31.2 MB 2.1 MB/s eta 0:00:09
   ---------------- ----------------------- 13.2/31.2 MB 2.1 MB/s eta 0:00:09
   ----------------- ---------------------- 13.3/31.2 MB 2.1 MB/s eta 0:00:09
   ----------------- ---------------------- 13.4/31.2 MB 2.1 MB/s eta 0:00:09
   ----------------- ---------------------- 13.5/31.2 MB 2.1 MB/s eta 0:00:09
   ----------------- ---------------------- 13.6/31.2 MB 2.1 MB/s eta 0:00:09
   ----------------- ---------------------- 13.6/31.2 MB 2.1 MB/s eta 0:00:09
   ----------------- ---------------------- 13.8/31.2 MB 2.1 MB/s eta 0:00:09
   ----------------- ---------------------- 13.9/31.2 MB 2.1 MB/s eta 0:00:09
   ----------------- ---------------------- 14.0/31.2 MB 2.1 MB/s eta 0:00:09
   ------------------ --------------------- 14.1/31.2 MB 2.1 MB/s eta 0:00:09
   ------------------ --------------------- 14.2/31.2 MB 2.1 MB/s eta 0:00:09
   ------------------ --------------------- 14.3/31.2 MB 2.1 MB/s eta 0:00:09
   ------------------ --------------------- 14.4/31.2 MB 2.1 MB/s eta 0:00:09
   ------------------ --------------------- 14.5/31.2 MB 2.1 MB/s eta 0:00:09
   ------------------ --------------------- 14.6/31.2 MB 2.1 MB/s eta 0:00:09
   ------------------ --------------------- 14.7/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------ --------------------- 14.8/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------- -------------------- 14.9/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------- -------------------- 15.0/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------- -------------------- 15.1/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------- -------------------- 15.2/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------- -------------------- 15.3/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------- -------------------- 15.4/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------- -------------------- 15.4/31.2 MB 2.1 MB/s eta 0:00:08
   ------------------- -------------------- 15.5/31.2 MB 2.1 MB/s eta 0:00:08
   -------------------- ------------------- 15.7/31.2 MB 2.1 MB/s eta 0:00:08
   -------------------- ------------------- 15.8/31.2 MB 2.1 MB/s eta 0:00:08
   -------------------- ------------------- 15.9/31.2 MB 2.1 MB/s eta 0:00:08
   -------------------- ------------------- 16.0/31.2 MB 2.1 MB/s eta 0:00:08
   -------------------- ------------------- 16.1/31.2 MB 2.1 MB/s eta 0:00:08
   -------------------- ------------------- 16.2/31.2 MB 2.1 MB/s eta 0:00:08
   -------------------- ------------------- 16.3/31.2 MB 2.1 MB/s eta 0:00:08
   --------------------- ------------------ 16.4/31.2 MB 2.1 MB/s eta 0:00:08
   --------------------- ------------------ 16.5/31.2 MB 2.1 MB/s eta 0:00:08
   --------------------- ------------------ 16.7/31.2 MB 2.1 MB/s eta 0:00:08
   --------------------- ------------------ 16.7/31.2 MB 2.1 MB/s eta 0:00:08
   --------------------- ------------------ 16.8/31.2 MB 2.1 MB/s eta 0:00:07
   --------------------- ------------------ 16.9/31.2 MB 2.1 MB/s eta 0:00:07
   --------------------- ------------------ 17.0/31.2 MB 2.1 MB/s eta 0:00:07
   --------------------- ------------------ 17.1/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 17.2/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 17.3/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 17.4/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 17.5/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 17.6/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 17.7/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 17.8/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 17.9/31.2 MB 2.1 MB/s eta 0:00:07
   ---------------------- ----------------- 18.0/31.2 MB 2.1 MB/s eta 0:00:07
   ----------------------- ---------------- 18.1/31.2 MB 2.1 MB/s eta 0:00:07
   ----------------------- ---------------- 18.2/31.2 MB 2.1 MB/s eta 0:00:07
   ----------------------- ---------------- 18.2/31.2 MB 2.1 MB/s eta 0:00:07
   ----------------------- ---------------- 18.3/31.2 MB 2.0 MB/s eta 0:00:07
   ----------------------- ---------------- 18.4/31.2 MB 2.0 MB/s eta 0:00:07
   ----------------------- ---------------- 18.5/31.2 MB 2.0 MB/s eta 0:00:07
   ----------------------- ---------------- 18.6/31.2 MB 2.0 MB/s eta 0:00:07
   ----------------------- ---------------- 18.7/31.2 MB 2.0 MB/s eta 0:00:07
   ------------------------ --------------- 18.8/31.2 MB 2.0 MB/s eta 0:00:07
   ------------------------ --------------- 18.8/31.2 MB 2.0 MB/s eta 0:00:07
   ------------------------ --------------- 19.0/31.2 MB 2.0 MB/s eta 0:00:07
   ------------------------ --------------- 19.1/31.2 MB 2.0 MB/s eta 0:00:07
   ------------------------ --------------- 19.2/31.2 MB 2.0 MB/s eta 0:00:07
   ------------------------ --------------- 19.2/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------ --------------- 19.3/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------ --------------- 19.3/31.2 MB 2.0 MB/s eta 0:00:07
   ------------------------ --------------- 19.4/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------ --------------- 19.4/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------ --------------- 19.5/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------- -------------- 19.6/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------- -------------- 19.7/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------- -------------- 19.8/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------- -------------- 19.9/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------- -------------- 19.9/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------- -------------- 20.0/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------- -------------- 20.1/31.2 MB 2.0 MB/s eta 0:00:06
   ------------------------- -------------- 20.2/31.2 MB 1.9 MB/s eta 0:00:06
   ------------------------- -------------- 20.2/31.2 MB 1.9 MB/s eta 0:00:06
   ------------------------- -------------- 20.3/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.4/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.4/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.5/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.6/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.6/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.7/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.7/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.8/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 20.9/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 21.0/31.2 MB 1.9 MB/s eta 0:00:06
   -------------------------- ------------- 21.0/31.2 MB 1.9 MB/s eta 0:00:06
   --------------------------- ------------ 21.1/31.2 MB 1.8 MB/s eta 0:00:06
   --------------------------- ------------ 21.2/31.2 MB 1.8 MB/s eta 0:00:06
   --------------------------- ------------ 21.2/31.2 MB 1.8 MB/s eta 0:00:06
   --------------------------- ------------ 21.4/31.2 MB 1.8 MB/s eta 0:00:06
   --------------------------- ------------ 21.5/31.2 MB 1.8 MB/s eta 0:00:06
   --------------------------- ------------ 21.6/31.2 MB 1.8 MB/s eta 0:00:06
   --------------------------- ------------ 21.6/31.2 MB 1.8 MB/s eta 0:00:06
   --------------------------- ------------ 21.7/31.2 MB 1.8 MB/s eta 0:00:06
   --------------------------- ------------ 21.8/31.2 MB 1.8 MB/s eta 0:00:06
   ---------------------------- ----------- 21.9/31.2 MB 1.8 MB/s eta 0:00:06
   ---------------------------- ----------- 22.0/31.2 MB 1.8 MB/s eta 0:00:06
   ---------------------------- ----------- 22.0/31.2 MB 1.8 MB/s eta 0:00:06
   ---------------------------- ----------- 22.1/31.2 MB 1.8 MB/s eta 0:00:06

In [31]:
pip install --upgrade librosa

Requirement already satisfied: librosa in c:\users\dell\anaconda3\lib\site-packages (0.11.0)
Requirement already satisfied: audioread>=2.1.9 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (3.0.1)
Requirement already satisfied: numba>=0.51.0 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (0.59.1)
Requirement already satisfied: numpy>=1.22.3 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (1.11.4)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (1.7.1)
Requirement already satisfied: joblib>=1.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (1.5.1)
Requirement already satisfied: decorator>=4.3.0 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (5.1.1)
Requirement already satisfied: soundfile>=0.12.1 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (0.13.1)
Requirement already satisfied: pooch>=1.1 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (1.0.0)
Requirement already satisfied: typing_extensions>=4.1.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from librosa) (4.14.1)
Requirement already satisfied: lazy_loader>=0.1 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (0.4)
Requirement already satisfied: msgpack>=1.0 in c:\users\dell\anaconda3\lib\site-packages (from librosa) (1.0.3)
Requirement already satisfied: packaging in c:\users\dell\appdata\roaming\python\python312\site-packages (from lazy_loader>=0.1->librosa) (25.0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in c:\users\dell\anaconda3\lib\site-packages (from numba>=0.51.0->librosa) (0.42.0)
Requirement already satisfied: platformdirs>=2.5.0 in c:\users\dell\anaconda3\lib\site-packages (from pooch>=1.1->librosa) (3.10.0)
Requirement already satisfied: requests>=2.19.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pooch>=1.1->librosa) (2.32.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\users\dell\anaconda3\lib\site-packages (from soundfile>=0.12.1->librosa) (1.16.0)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.21)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\appdata\roaming\python\python312\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\roaming\python\python312\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\appdata\roaming\python\python312\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2025.7.14)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import librosa
y, sr = librosa.load(r"C:\Users\DELL\Downloads\audios\copy.mp3")
print("Loaded successfully:", sr, "Hz")

C:\Users\DELL\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated and will be removed in a future release
  "class": algorithms.Blowfish,

Loaded successfully: 22050 Hz

In [3]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [5]:
import librosa
import numpy as np

def extract_audio_features(audio_path):

    y, sr = librosa.load(audio_path)
    
    tempo, _ = librosa.beat.beat_track(y=y, sr=sr)
    speech_rate_score = tempo / 200  

    rms = librosa.feature.rms(y=y).flatten()
    energy_score = np.mean(rms)


    confidence_score = np.clip(1 - np.std(rms) / np.mean(rms), 0, 1)


    pitches, magnitudes = librosa.piptrack(y=y, sr=sr)
    pitch_values = pitches[magnitudes > np.median(magnitudes)]
    pitch_mean = np.mean(pitch_values) if len(pitch_values) > 0 else 0


    pitch_std = np.std(pitch_values) if len(pitch_values) > 0 else 0

    return {
        "speech_rate_score": round(float(speech_rate_score), 3),
        "energy_score": round(float(energy_score), 3),
        "confidence_score": round(float(confidence_score), 3),
        "pitch_mean": round(float(pitch_mean), 3),
        "pitch_std": round(float(pitch_std), 3)
    }


audio_file = r"C:\Users\DELL\Downloads\audios\copy.mp3"
features = extract_audio_features(audio_file)

for key, value in features.items():
    print(f"{key}: {value}")

speech_rate_score: 0.615
energy_score: 0.034
confidence_score: 0.434
pitch_mean: 1114.865
pitch_std: 1132.963

In [4]:
import os
import librosa
import numpy as np
import pandas as pd

def extract_audio_features(audio_path):
    y, sr = librosa.load(audio_path)

    
    tempo, _ = librosa.beat.beat_track(y=y, sr=sr)
    speech_rate_score = tempo / 200  

    # الطاقة (energy)
    rms = librosa.feature.rms(y=y).flatten()
    energy_score = np.mean(rms)

    # الثقة (confidence)
    confidence_score = np.clip(1 - np.std(rms) / np.mean(rms), 0, 1)

    # درجة الصوت (pitch)
    pitches, magnitudes = librosa.piptrack(y=y, sr=sr)
    pitch_values = pitches[magnitudes > np.median(magnitudes)]
    pitch_mean = np.mean(pitch_values) if len(pitch_values) > 0 else 0
    pitch_std = np.std(pitch_values) if len(pitch_values) > 0 else 0

    return {
        "speech_rate_score": round(float(speech_rate_score), 3),
        "energy_score": round(float(energy_score), 3),
        "confidence_score": round(float(confidence_score), 3),
        "pitch_mean": round(float(pitch_mean), 3),
        "pitch_std": round(float(pitch_std), 3)
    }

# مسار الفولدر اللي فيه الملفات الصوتية
folder_path = r"C:\Users\DELL\Downloads\audios"

# إنشاء DataFrame فاضي
results = []

# المرور على كل الملفات في الفولدر
for filename in os.listdir(folder_path):
    if filename.lower().endswith(('.mp3', '.wav', '.m4a', '.flac')):
        file_path = os.path.join(folder_path, filename)
        print(f"Analyzing {filename}...")
        try:
            features = extract_audio_features(file_path)
            features["file_name"] = filename
            results.append(features)
        except Exception as e:
            print(f"Error processing {filename}: {e}")

# تحويل النتائج إلى DataFrame
df = pd.DataFrame(results)

# ترتيب الأعمدة
df = df[["file_name", "speech_rate_score", "energy_score", "confidence_score", "pitch_mean", "pitch_std"]]

# عرض النتيجة
print("\n✅ Analysis Complete!\n")
print(df)

# حفظها في ملف Excel (اختياري)
output_path = os.path.join(folder_path, "audio_features.xlsx")
df.to_excel(output_path, index=False)
print(f"\n📁 Saved results to: {output_path}")

Analyzing a1.mp3...

C:\Users\DELL\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated and will be removed in a future release
  "class": algorithms.Blowfish,
C:\Users\DELL\AppData\Local\Temp\ipykernel_8104\219279313.py:27: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  "speech_rate_score": round(float(speech_rate_score), 3),

Analyzing a10.mp3...
Analyzing a100.mp3...
Analyzing a101.mp3...
Analyzing a102.mp3...
Analyzing a103.mp3...
Analyzing a104.mp3...
Analyzing a105.mp3...
Analyzing a106.mp3...
Analyzing a107.mp3...
Analyzing a108.mp3...
Analyzing a109.mp3...
Analyzing a11.mp3...
Analyzing a110.mp3...
Analyzing a111.mp3...
Analyzing a112.mp3...
Analyzing a113.mp3...
Analyzing a114.mp3...
Analyzing a115.mp3...
Analyzing a116.mp3...
Analyzing a117.mp3...
Analyzing a118.mp3...
Analyzing a119.mp3...
Analyzing a12.mp3...
Analyzing a120.mp3...
Analyzing a121.mp3...
Analyzing a122.mp3...
Analyzing a123.mp3...
Analyzing a13.mp3...
Analyzing a14.mp3...
Analyzing a15.mp3...
Analyzing a16.mp3...

KeyboardInterrupt:

In [8]:
import pandas as pd
import re

# 📂 تحميل البيانات من ملف Excel
file_path = r"C:\Users\DELL\Downloads\audios\audio_features.xlsx"  # ← غيّري المسار حسب مكان الملف
df = pd.read_excel(file_path)

# 🧮 إضافة عمود جديد فيه الرقم المستخرج من اسم الملف
df["file_number"] = df["file_name"].apply(lambda x: int(re.search(r'\d+', x).group()))

# 🔢 ترتيب DataFrame بناءً على الرقم
df = df.sort_values(by="file_number").reset_index(drop=True)

# 🗑️ حذف العمود المساعد (اختياري)
df = df.drop(columns=["file_number"])

# 💾 حفظ النتيجة المرتبة في ملف جديد (أو نفس الملف)
output_path = r"C:\Users\DELL\Downloads\audio_features_sorted.xlsx"
df.to_excel(output_path, index=False)


print(df.head(10))

✅ تم ترتيب الملفات وحفظها في:
C:\Users\DELL\Downloads\audio_features_sorted.xlsx

أول 10 صفوف بعد الترتيب:
  file_name  speech_rate_score  energy_score  confidence_score  pitch_mean  \
0    a1.mp3              0.615         0.030             0.372    1622.074
1    a2.mp3              0.718         0.210             0.166    1203.216
2    a3.mp3              0.497         0.491             0.418    1413.585
3    a4.mp3              0.479         0.543             0.520    1476.508
4    a5.mp3              0.646         0.068             0.442    1275.993
5    a6.mp3              0.680         0.066             0.412    1353.844
6    a7.mp3              0.615         0.067             0.397    1281.674
7    a8.mp3              0.538         0.030             0.356    1213.792
8    a9.mp3              0.680         0.006             0.000    1433.709
9   a10.mp3              0.417         0.063             0.084    1458.296

   pitch_std
0   1060.125
1   1014.420
2   1068.160
3   1058.691
4    850.366
5    894.869
6    851.132
7    825.546
8   1003.447
9   1103.361

In [10]:
df

,file_name,speech_rate_score,energy_score,confidence_score,pitch_mean,pitch_std
0,a1.mp3,0.615,0.030,0.372,1622.074,1060.125
1,a2.mp3,0.718,0.210,0.166,1203.216,1014.420
2,a3.mp3,0.497,0.491,0.418,1413.585,1068.160
3,a4.mp3,0.479,0.543,0.520,1476.508,1058.691
4,a5.mp3,0.646,0.068,0.442,1275.993,850.366
...,...,...,...,...,...,...
118,a119.mp3,0.615,0.141,0.421,1091.399,760.606
119,a120.mp3,0.760,0.091,0.189,1165.404,847.541
120,a121.mp3,0.680,0.130,0.312,1185.736,998.329
121,a122.mp3,0.718,0.158,0.217,600.016,406.044
122,a123.mp3,0.615,0.112,0.304,886.066,558.534

In [19]:
import os
import librosa
import numpy as np
import pandas as pd

# 📂 مسار الفولدر اللي فيه ملفات الصوت
audio_folder = r"C:\Users\DELL\Downloads\audios"

# 🧾 إنشاء قائمة لتخزين البيانات
data = []

# 🔁 نقرأ كل ملف صوت في الفولدر
for file in os.listdir(audio_folder):
    if file.lower().endswith(('.mp3', '.wav', '.m4a', '.flac')):
        file_path = os.path.join(audio_folder, file)
        print(f"🎧 Analyzing {file}...")

        try:
            # قراءة الملف الصوتي
            y, sr = librosa.load(file_path, sr=None)

            # استخراج MFCC features
            mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)

            # نأخذ المتوسط عبر الزمن (عشان يكون تمثيل ثابت)
            mfcc_mean = np.mean(mfcc, axis=1)

            # إضافة البيانات إلى القائمة
            data.append({
                "audio_file": file,
                "embedding": mfcc_mean.tolist()
            })

        except Exception as e:
            print(f"⚠️ Error processing {file}: {e}")

# 🧠 نحول إلى DataFrame
df2 = pd.DataFrame(data)

# 💾 نحفظ النتائج في Excel
output_path = r"C:\Users\DELL\Downloads\audio_embeddings.xlsx"
df2.to_excel(output_path, index=False)


# نعرض أول 5 صفوف
print(df2.head())

🎧 Analyzing a1.mp3...
🎧 Analyzing a10.mp3...
🎧 Analyzing a100.mp3...
🎧 Analyzing a101.mp3...
🎧 Analyzing a102.mp3...
🎧 Analyzing a103.mp3...
🎧 Analyzing a104.mp3...
🎧 Analyzing a105.mp3...
🎧 Analyzing a106.mp3...
🎧 Analyzing a107.mp3...
🎧 Analyzing a108.mp3...
🎧 Analyzing a109.mp3...
🎧 Analyzing a11.mp3...
🎧 Analyzing a110.mp3...
🎧 Analyzing a111.mp3...
🎧 Analyzing a112.mp3...
🎧 Analyzing a113.mp3...
🎧 Analyzing a114.mp3...
🎧 Analyzing a115.mp3...
🎧 Analyzing a116.mp3...
🎧 Analyzing a117.mp3...
🎧 Analyzing a118.mp3...
🎧 Analyzing a119.mp3...
🎧 Analyzing a12.mp3...
🎧 Analyzing a120.mp3...
🎧 Analyzing a121.mp3...
🎧 Analyzing a122.mp3...
🎧 Analyzing a123.mp3...
🎧 Analyzing a13.mp3...
🎧 Analyzing a14.mp3...
🎧 Analyzing a15.mp3...
🎧 Analyzing a16.mp3...
🎧 Analyzing a17.mp3...
🎧 Analyzing a18.mp3...
🎧 Analyzing a19.mp3...
🎧 Analyzing a2.mp3...
🎧 Analyzing a20.mp3...
🎧 Analyzing a21.mp3...
🎧 Analyzing a22.mp3...
🎧 Analyzing a23.mp3...
🎧 Analyzing a24.mp3...
🎧 Analyzing a25.mp3...
🎧 Analyzing a26.mp3...
🎧 Analyzing a27.mp3...
🎧 Analyzing a28.mp3...
🎧 Analyzing a29.mp3...
🎧 Analyzing a3.mp3...
🎧 Analyzing a30.mp3...
🎧 Analyzing a31.mp3...
🎧 Analyzing a32.mp3...
🎧 Analyzing a33.mp3...
🎧 Analyzing a34.mp3...
🎧 Analyzing a35.mp3...
🎧 Analyzing a36.mp3...
🎧 Analyzing a37.mp3...
🎧 Analyzing a38.mp3...
🎧 Analyzing a39.mp3...
🎧 Analyzing a4.mp3...
🎧 Analyzing a40.mp3...
🎧 Analyzing a41.mp3...
🎧 Analyzing a42.mp3...
🎧 Analyzing a43.mp3...
🎧 Analyzing a44.mp3...
🎧 Analyzing a45.mp3...
🎧 Analyzing a46.mp3...
🎧 Analyzing a47.mp3...
🎧 Analyzing a48.mp3...
🎧 Analyzing a49.mp3...
🎧 Analyzing a5.mp3...
🎧 Analyzing a50.mp3...
🎧 Analyzing a51.mp3...
🎧 Analyzing a52.mp3...
🎧 Analyzing a53.mp3...
🎧 Analyzing a54.mp3...
🎧 Analyzing a55.mp3...
🎧 Analyzing a56.mp3...
🎧 Analyzing a57.mp3...
🎧 Analyzing a58.mp3...
🎧 Analyzing a59.mp3...
🎧 Analyzing a6.mp3...
🎧 Analyzing a60.mp3...
🎧 Analyzing a61.mp3...
🎧 Analyzing a62.mp3...
🎧 Analyzing a63.mp3...
🎧 Analyzing a64.mp3...
🎧 Analyzing a65.mp3...
🎧 Analyzing a66.mp3...
🎧 Analyzing a67.mp3...
🎧 Analyzing a68.mp3...
🎧 Analyzing a69.mp3...
🎧 Analyzing a7.mp3...
🎧 Analyzing a70.mp3...
🎧 Analyzing a71.mp3...
🎧 Analyzing a72.mp3...
🎧 Analyzing a73.mp3...
🎧 Analyzing a74.mp3...
🎧 Analyzing a75.mp3...
🎧 Analyzing a76.mp3...
🎧 Analyzing a77.mp3...
🎧 Analyzing a78.mp3...
🎧 Analyzing a79.mp3...
🎧 Analyzing a8.mp3...
🎧 Analyzing a80.mp3...
🎧 Analyzing a81.mp3...
🎧 Analyzing a82.mp3...
🎧 Analyzing a83.mp3...
🎧 Analyzing a84.mp3...
🎧 Analyzing a85.mp3...
🎧 Analyzing a86.mp3...
🎧 Analyzing a87.mp3...
🎧 Analyzing a88.mp3...
🎧 Analyzing a89.mp3...
🎧 Analyzing a9.mp3...
🎧 Analyzing a90.mp3...
🎧 Analyzing a91.mp3...
🎧 Analyzing a92.mp3...
🎧 Analyzing a93.mp3...
🎧 Analyzing a94.mp3...
🎧 Analyzing a95.mp3...
🎧 Analyzing a96.mp3...
🎧 Analyzing a97.mp3...
🎧 Analyzing a98.mp3...
🎧 Analyzing a99.mp3...
  audio_file                                          embedding
0     a1.mp3  [-325.5080261230469, 152.41494750976562, -53.9...
1    a10.mp3  [-286.1631164550781, 143.0788116455078, -40.96...
2   a100.mp3  [-266.9715881347656, 165.42047119140625, 17.64...
3   a101.mp3  [-283.7193603515625, 135.31690979003906, 7.122...
4   a102.mp3  [-202.64462280273438, 161.69424438476562, -13....

In [5]:
df2

    audio_file                                          embedding
0       a1.mp3  [-325.5080261230469, 152.41494750976562, -53.9...
1      a10.mp3  [-286.1631164550781, 143.0788116455078, -40.96...
2     a100.mp3  [-266.9715881347656, 165.42047119140625, 17.64...
3     a101.mp3  [-283.7193603515625, 135.31690979003906, 7.122...
4     a102.mp3  [-202.64462280273438, 161.69424438476562, -13....
..         ...                                                ...
118    a95.mp3  [-233.5364227294922, 157.3232879638672, -25.99...
119    a96.mp3  [-460.83233642578125, 155.9681854248047, -36.2...
120    a97.mp3  [-309.2043151855469, 179.07579040527344, -12.1...
121    a98.mp3  [-273.2735290527344, 117.49581146240234, -9.22...
122    a99.mp3  [-331.8119812011719, 172.80325317382812, 4.938...

[123 rows x 2 columns]

In [23]:
import re

df2["file_number"] = df2["audio_file"].apply(lambda x: int(re.search(r'\d+', x).group()) if re.search(r'\d+', x) else -1)


df2 = df2.sort_values(by="file_number").reset_index(drop=True)

df2 = df2.drop(columns=["file_number"])


output_path = r"C:\Users\DELL\Downloads\audio_embeddings_sorted.xlsx"
df2.to_excel(output_path, index=False)

print(df2.head())

  audio_file                                          embedding
0     a1.mp3  [-325.5080261230469, 152.41494750976562, -53.9...
1     a2.mp3  [-161.26507568359375, 145.8347625732422, -29.8...
2     a3.mp3  [-36.562747955322266, 137.6844024658203, -44.8...
3     a4.mp3  [-16.832063674926758, 135.2333984375, -49.2888...
4     a5.mp3  [-220.19400024414062, 135.56109619140625, -37....

In [25]:
df2

    audio_file                                          embedding
0       a1.mp3  [-325.5080261230469, 152.41494750976562, -53.9...
1       a2.mp3  [-161.26507568359375, 145.8347625732422, -29.8...
2       a3.mp3  [-36.562747955322266, 137.6844024658203, -44.8...
3       a4.mp3  [-16.832063674926758, 135.2333984375, -49.2888...
4       a5.mp3  [-220.19400024414062, 135.56109619140625, -37....
..         ...                                                ...
118   a119.mp3  [-190.72781372070312, 195.51739501953125, -8.0...
119   a120.mp3  [-240.15785217285156, 160.17910766601562, -12....
120   a121.mp3  [-223.87933349609375, 145.32664489746094, -31....
121   a122.mp3  [-287.2694091796875, 174.93844604492188, 46.05...
122   a123.mp3  [-246.5943603515625, 186.9765625, -6.903068065...

[123 rows x 2 columns]

In [47]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error
import pandas as pd
import numpy as np
import ast

# 🧩 تحميل البيانات
X = pd.read_excel(r"C:\Users\DELL\Downloads\audio_embeddings_sorted.xlsx")
y = pd.read_excel(r"C:\Users\DELL\Downloads\audio_features_sorted.xlsx")

# 🧮 تحويل العمود النصي إلى قائمة أرقام
X['embedding'] = X['embedding'].apply(ast.literal_eval)
X_expanded = pd.DataFrame(X['embedding'].tolist())

# 🎯 تحديد الأعمدة المستهدفة (الـ targets)
target_cols = ["speech_rate_score", "energy_score", "confidence_score", "pitch_mean", "pitch_std"]
y = y[target_cols]

# ✂️ تقسيم البيانات إلى تدريب واختبار
X_train, X_test, y_train, y_test = train_test_split(X_expanded, y, test_size=0.2, random_state=42)

# 🌳 إنشاء الموديل
model = RandomForestRegressor(random_state=42)

# 🏋️‍♀️ تدريب الموديل
model.fit(X_train, y_train)

# 🔮 التنبؤ
y_pred = model.predict(X_test)

# 📏 تقييم الأداء على مجموعة الاختبار
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
accuracy = (1 - (mae / y_test.mean().mean())) * 100

print(" Performance on Test Set:")
print(f" R² Score: {r2:.3f}")
print(f" Mean Absolute Error: {mae:.3f}")
print(f" Approximate Accuracy: {accuracy:.2f}%")


print("\n Cross-Validation Results:")
cv_scores = cross_val_score(model, X_expanded, y, cv=5, scoring='r2')

print("Cross-validation R² scores:", cv_scores)
print("Mean R² (CV):", np.mean(cv_scores))
print("Std Dev R² (CV):", np.std(cv_scores))

 Performance on Test Set:
 R² Score: 0.372
 Mean Absolute Error: 22.009
 Approximate Accuracy: 94.51%

 Cross-Validation Results:
Cross-validation R² scores: [0.52964112 0.30697908 0.21794431 0.4530433  0.1054125 ]
Mean R² (CV): 0.3226040613085752
Std Dev R² (CV): 0.1537847291572327

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
import pandas as pd
import ast
import xgboost as xgb

# تحميل ملفات الـ embeddings (X) والـ features (Y)
X = pd.read_excel(r"C:\Users\DELL\Downloads\audio_embeddings_sorted.xlsx")
y = pd.read_excel(r"C:\Users\DELL\Downloads\audio_features_sorted.xlsx")

# تحويل عمود الـ embeddings من string إلى list of numbers
X['embedding'] = X['embedding'].apply(ast.literal_eval)
X_expanded = pd.DataFrame(X['embedding'].tolist())  # تحويلها لأعمدة رقمية

# تحديد الـ target columns (y)
target_cols = ["speech_rate_score", "energy_score", "confidence_score", "pitch_mean", "pitch_std"]
y = y[target_cols]

# تقسيم البيانات إلى تدريب واختبار
X_train, X_test, y_train, y_test = train_test_split(X_expanded, y, test_size=0.2, random_state=42)

# إنشاء موديل XGBoost Regressor
model = xgb.XGBRegressor(
    objective='reg:squarederror',
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

accuracy = (1 - (mae / y_test.mean().mean())) * 100

print(f" R² Score: {r2:.3f}")
print(f" Mean Absolute Error: {mae:.3f}")
print(f" Approximate Model Accuracy: {accuracy:.2f}%")

 R² Score: 0.505
 Mean Absolute Error: 21.825
 Approximate Model Accuracy: 94.55%

In [13]:
import joblib
model_path = r"C:\Users\DELL\Downloads\xgboost_model.pkl"
joblib.dump(model, model_path)

print(f"💾 Model saved successfully at: {model_path}")

💾 Model saved successfully at: C:\Users\DELL\Downloads\xgboost_model.pkl

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.ensemble import ExtraTreesRegressor
import pandas as pd
import ast

# تحميل ملفات الـ embeddings (X) والـ features (Y)
X = pd.read_excel(r"C:\Users\DELL\Downloads\audio_embeddings_sorted.xlsx")
y = pd.read_excel(r"C:\Users\DELL\Downloads\audio_features_sorted.xlsx")

# تحويل عمود الـ embeddings من string إلى list of numbers
X['embedding'] = X['embedding'].apply(ast.literal_eval)
X_expanded = pd.DataFrame(X['embedding'].tolist())  # تحويلها لأعمدة رقمية

# تحديد الـ target columns (y)
target_cols = ["speech_rate_score", "energy_score", "confidence_score", "pitch_mean", "pitch_std"]
y = y[target_cols]

X_train, X_test, y_train, y_test = train_test_split(X_expanded, y, test_size=0.2, random_state=42)

model = ExtraTreesRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    random_state=42,
    n_jobs=-1  # لتسريع التدريب
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

accuracy = (1 - (mae / y_test.mean().mean())) * 100

print(f" R² Score: {r2:.3f}")
print(f" Mean Absolute Error: {mae:.3f}")
print(f" Approximate Model Accuracy: {accuracy:.2f}%")

 R² Score: 0.418
 Mean Absolute Error: 21.566
 Approximate Model Accuracy: 94.62%

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
from catboost import CatBoostRegressor
import pandas as pd
import ast

# تحميل ملفات الـ embeddings (X) والـ features (Y)
X = pd.read_excel(r"C:\Users\DELL\Downloads\audio_embeddings_sorted.xlsx")
y = pd.read_excel(r"C:\Users\DELL\Downloads\audio_features_sorted.xlsx")

# تحويل عمود الـ embeddings من string إلى list of numbers
X['embedding'] = X['embedding'].apply(ast.literal_eval)
X_expanded = pd.DataFrame(X['embedding'].tolist())  # أعمدة رقمية

# تحديد الـ target columns (y)
target_cols = ["speech_rate_score", "energy_score", "confidence_score", "pitch_mean", "pitch_std"]
y = y[target_cols]

# تحويل y إلى numpy array
y = y.values

# تقسيم البيانات إلى تدريب واختبار
X_train, X_test, y_train, y_test = train_test_split(X_expanded, y, test_size=0.2, random_state=42)

# إنشاء موديل CatBoost Regressor
model = CatBoostRegressor(
    iterations=500,
    learning_rate=0.05,
    depth=8,
    loss_function='MultiRMSE',  # لعدة target
    random_seed=42,
    verbose=100
)

# تدريب الموديل
model.fit(X_train, y_train)

# التنبؤ
y_pred = model.predict(X_test)

# تقييم الأداء
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
accuracy = (1 - (mae / y_test.mean().mean())) * 100

print(f"R² Score: {r2:.3f}")
print(f"Mean Absolute Error: {mae:.3f}")
print(f"Approximate Model Accuracy: {accuracy:.2f}%")

0:	learn: 317.8674299	total: 338ms	remaining: 2m 48s
100:	learn: 75.9211177	total: 3.58s	remaining: 14.1s
200:	learn: 22.0986907	total: 6.73s	remaining: 10s
300:	learn: 7.7643803	total: 9.9s	remaining: 6.54s
400:	learn: 3.4182941	total: 13s	remaining: 3.2s
499:	learn: 1.7136598	total: 16s	remaining: 0us
R² Score: 0.400
Mean Absolute Error: 27.394
Approximate Model Accuracy: 93.16%

In [9]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\dell\appdata\roaming\python\python312\site-packages (from catboost) (3.10.5)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in c:\users\dell\appdata\roaming\python\python312\site-packages (from catboost) (2.3.1)
Requirement already satisfied: scipy in c:\users\dell\appdata\roaming\python\python312\site-packages (from catboost) (1.11.4)
Requirement already satisfied: plotly in c:\users\dell\anaconda3\lib\site-packages (from catboost) (5.22.0)
Requirement already satisfied: six in c:\users\dell\appdata\roaming\python\python312\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\dell\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (3.2.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from plotly->catboost) (9.1.2)
Downloading catboost-1.2.8-cp312-cp312-win_amd64.whl (102.4 MB)
   ---------------------------------------- 0.0/102.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/102.4 MB 1.4 MB/s eta 0:01:15
   ---------------------------------------- 0.0/102.4 MB 393.8 kB/s eta 0:04:20
   ---------------------------------------- 0.1/102.4 MB 751.6 kB/s eta 0:02:17
   ---------------------------------------- 0.2/102.4 MB 821.4 kB/s eta 0:02:05
   ---------------------------------------- 0.2/102.4 MB 821.4 kB/s eta 0:02:05
   ---------------------------------------- 0.2/102.4 MB 838.1 kB/s eta 0:02:02
   ---------------------------------------- 0.3/102.4 MB 967.8 kB/s eta 0:01:46
   ---------------------------------------- 0.4/102.4 MB 1.1 MB/s eta 0:01:32
   ---------------------------------------- 0.5/102.4 MB 1.2 MB/s eta 0:01:24
   ---------------------------------------- 0.6/102.4 MB 1.3 MB/s eta 0:01:21
   ---------------------------------------- 0.6/102.4 MB 1.3 MB/s eta 0:01:21
   ---------------------------------------- 0.6/102.4 MB 1.3 MB/s eta 0:01:21
   ---------------------------------------- 0.6/102.4 MB 1.3 MB/s eta 0:01:21
   ---------------------------------------- 0.6/102.4 MB 1.3 MB/s eta 0:01:21
   ---------------------------------------- 0.6/102.4 MB 1.3 MB/s eta 0:01:21
   ---------------------------------------- 0.6/102.4 MB 1.3 MB/s eta 0:01:21
   ---------------------------------------- 0.6/102.4 MB 1.3 MB/s eta 0:01:21
   ---------------------------------------- 0.6/102.4 MB 729.7 kB/s eta 0:02:20
   ---------------------------------------- 1.0/102.4 MB 1.1 MB/s eta 0:01:34
   ---------------------------------------- 1.0/102.4 MB 1.1 MB/s eta 0:01:34
   ---------------------------------------- 1.1/102.4 MB 1.1 MB/s eta 0:01:31
   ---------------------------------------- 1.2/102.4 MB 1.1 MB/s eta 0:01:30
   ---------------------------------------- 1.3/102.4 MB 1.2 MB/s eta 0:01:28
    --------------------------------------- 1.3/102.4 MB 1.2 MB/s eta 0:01:27
    --------------------------------------- 1.4/102.4 MB 1.2 MB/s eta 0:01:26
    --------------------------------------- 1.5/102.4 MB 1.2 MB/s eta 0:01:23
    --------------------------------------- 1.6/102.4 MB 1.2 MB/s eta 0:01:21
    --------------------------------------- 1.6/102.4 MB 1.2 MB/s eta 0:01:22
    --------------------------------------- 1.6/102.4 MB 1.2 MB/s eta 0:01:22
    --------------------------------------- 1.7/102.4 MB 1.1 MB/s eta 0:01:28
    --------------------------------------- 1.9/102.4 MB 1.3 MB/s eta 0:01:20
    --------------------------------------- 1.9/102.4 MB 1.2 MB/s eta 0:01:21
    --------------------------------------- 2.0/102.4 MB 1.3 MB/s eta 0:01:19
    --------------------------------------- 2.1/102.4 MB 1.3 MB/s eta 0:01:17
    --------------------------------------- 2.2/102.4 MB 1.3 MB/s eta 0:01:17
    --------------------------------------- 2.3/102.4 MB 1.3 MB/s eta 0:01:16
    --------------------------------------- 2.4/102.4 MB 1.3 MB/s eta 0:01:15
    --------------------------------------- 2.5/102.4 MB 1.4 MB/s eta 0:01:14
    --------------------------------------- 2.5/102.4 MB 1.4 MB/s eta 0:01:14
    --------------------------------------- 2.5/102.4 MB 1.4 MB/s eta 0:01:14
    --------------------------------------- 2.5/102.4 MB 1.4 MB/s eta 0:01:14
   - -------------------------------------- 2.7/102.4 MB 1.3 MB/s eta 0:01:17
   - -------------------------------------- 2.9/102.4 MB 1.4 MB/s eta 0:01:13
   - -------------------------------------- 3.1/102.4 MB 1.4 MB/s eta 0:01:09
   - -------------------------------------- 3.2/102.4 MB 1.5 MB/s eta 0:01:08
   - -------------------------------------- 3.3/102.4 MB 1.5 MB/s eta 0:01:07
   - -------------------------------------- 3.4/102.4 MB 1.5 MB/s eta 0:01:07
   - -------------------------------------- 3.5/102.4 MB 1.5 MB/s eta 0:01:06
   - -------------------------------------- 3.6/102.4 MB 1.5 MB/s eta 0:01:05
   - -------------------------------------- 3.7/102.4 MB 1.5 MB/s eta 0:01:05
   - -------------------------------------- 3.8/102.4 MB 1.5 MB/s eta 0:01:05
   - -------------------------------------- 3.9/102.4 MB 1.5 MB/s eta 0:01:04
   - -------------------------------------- 4.0/102.4 MB 1.6 MB/s eta 0:01:03
   - -------------------------------------- 4.1/102.4 MB 1.6 MB/s eta 0:01:03
   - -------------------------------------- 4.2/102.4 MB 1.6 MB/s eta 0:01:03
   - -------------------------------------- 4.3/102.4 MB 1.6 MB/s eta 0:01:02
   - -------------------------------------- 4.4/102.4 MB 1.6 MB/s eta 0:01:02
   - -------------------------------------- 4.5/102.4 MB 1.6 MB/s eta 0:01:02
   - -------------------------------------- 4.6/102.4 MB 1.6 MB/s eta 0:01:01
   - -------------------------------------- 4.7/102.4 MB 1.6 MB/s eta 0:01:01
   - -------------------------------------- 4.8/102.4 MB 1.6 MB/s eta 0:01:01
   - -------------------------------------- 4.9/102.4 MB 1.6 MB/s eta 0:01:00
   - -------------------------------------- 5.0/102.4 MB 1.6 MB/s eta 0:01:00
   -- ------------------------------------- 5.1/102.4 MB 1.7 MB/s eta 0:00:59
   -- ------------------------------------- 5.2/102.4 MB 1.7 MB/s eta 0:00:59
   -- ------------------------------------- 5.4/102.4 MB 1.7 MB/s eta 0:00:59
   -- ------------------------------------- 5.4/102.4 MB 1.7 MB/s eta 0:00:59
   -- ------------------------------------- 5.6/102.4 MB 1.7 MB/s eta 0:00:58
   -- ------------------------------------- 5.7/102.4 MB 1.7 MB/s eta 0:00:58
   -- ------------------------------------- 5.8/102.4 MB 1.7 MB/s eta 0:00:58
   -- ------------------------------------- 5.9/102.4 MB 1.7 MB/s eta 0:00:58
   -- ------------------------------------- 6.0/102.4 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 6.1/102.4 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 6.2/102.4 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 6.3/102.4 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 6.4/102.4 MB 1.7 MB/s eta 0:00:56
   -- ------------------------------------- 6.5/102.4 MB 1.7 MB/s eta 0:00:56
   -- ------------------------------------- 6.6/102.4 MB 1.7 MB/s eta 0:00:56
   -- ------------------------------------- 6.7/102.4 MB 1.7 MB/s eta 0:00:56
   -- ------------------------------------- 6.8/102.4 MB 1.7 MB/s eta 0:00:55
   -- ------------------------------------- 6.9/102.4 MB 1.7 MB/s eta 0:00:55
   -- ------------------------------------- 7.0/102.4 MB 1.7 MB/s eta 0:00:55
   -- ------------------------------------- 7.1/102.4 MB 1.8 MB/s eta 0:00:55
   -- ------------------------------------- 7.2/102.4 MB 1.8 MB/s eta 0:00:55
   -- ------------------------------------- 7.3/102.4 MB 1.8 MB/s eta 0:00:55
   -- ------------------------------------- 7.4/102.4 MB 1.8 MB/s eta 0:00:54
   -- ------------------------------------- 7.5/102.4 MB 1.8 MB/s eta 0:00:54
   -- ------------------------------------- 7.6/102.4 MB 1.8 MB/s eta 0:00:54
   --- ------------------------------------ 7.7/102.4 MB 1.8 MB/s eta 0:00:54
   --- ------------------------------------ 7.8/102.4 MB 1.8 MB/s eta 0:00:54
   --- ------------------------------------ 8.0/102.4 MB 1.8 MB/s eta 0:00:54
   --- ------------------------------------ 8.1/102.4 MB 1.8 MB/s eta 0:00:53
   --- ------------------------------------ 8.2/102.4 MB 1.8 MB/s eta 0:00:53
   --- ------------------------------------ 8.3/102.4 MB 1.8 MB/s eta 0:00:53
   --- ------------------------------------ 8.4/102.4 MB 1.8 MB/s eta 0:00:53
   --- ------------------------------------ 8.5/102.4 MB 1.8 MB/s eta 0:00:53
   --- ------------------------------------ 8.6/102.4 MB 1.8 MB/s eta 0:00:53
   --- ------------------------------------ 8.7/102.4 MB 1.8 MB/s eta 0:00:53
   --- ------------------------------------ 8.8/102.4 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 8.9/102.4 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 9.0/102.4 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 9.1/102.4 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 9.2/102.4 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 9.3/102.4 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 9.4/102.4 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 9.5/102.4 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 9.6/102.4 MB 1.8 MB/s eta 0:00:51
   --- ------------------------------------ 9.7/102.4 MB 1.8 MB/s eta 0:00:51
   --- ------------------------------------ 9.8/102.4 MB 1.8 MB/s eta 0:00:51
   --- ------------------------------------ 9.9/102.4 MB 1.8 MB/s eta 0:00:51
   --- ------------------------------------ 10.0/102.4 MB 1.8 MB/s eta 0:00:51
   --- ------------------------------------ 10.1/102.4 MB 1.8 MB/s eta 0:00:51
   --- ------------------------------------ 10.2/102.4 MB 1.8 MB/s eta 0:00:51
   ---- ----------------------------------- 10.3/102.4 MB 1.9 MB/s eta 0:00:50
   ---- ----------------------------------- 10.4/102.4 MB 1.9 MB/s eta 0:00:49
   ---- ----------------------------------- 10.5/102.4 MB 1.9 MB/s eta 0:00:49
   ---- ----------------------------------- 10.6/102.4 MB 1.9 MB/s eta 0:00:49
   ---- ----------------------------------- 10.7/102.4 MB 1.9 MB/s eta 0:00:49
   ---- ----------------------------------- 10.8/102.4 MB 2.0 MB/s eta 0:00:46
   ---- ----------------------------------- 10.9/102.4 MB 2.0 MB/s eta 0:00:46
   ---- ----------------------------------- 11.0/102.4 MB 2.0 MB/s eta 0:00:46
   ---- ----------------------------------- 11.1/102.4 MB 2.0 MB/s eta 0:00:46
   ---- ----------------------------------- 11.2/102.4 MB 2.0 MB/s eta 0:00:46
   ---- ----------------------------------- 11.3/102.4 MB 2.0 MB/s eta 0:00:46
   ---- ----------------------------------- 11.4/102.4 MB 2.0 MB/s eta 0:00:46
   ---- ----------------------------------- 11.6/102.4 MB 2.0 MB/s eta 0:00:45
   ---- ----------------------------------- 11.7/102.4 MB 2.0 MB/s eta 0:00:45
   ---- ----------------------------------- 11.8/102.4 MB 2.0 MB/s eta 0:00:45
   ---- ----------------------------------- 11.9/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.0/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.1/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.2/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.2/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.4/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.5/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.5/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.6/102.4 MB 2.1 MB/s eta 0:00:44
   ---- ----------------------------------- 12.8/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 12.8/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 13.0/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 13.1/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 13.1/102.4 MB 2.1 MB/s eta 0:00:44
   ----- ---------------------------------- 13.3/102.4 MB 2.1 MB/s eta 0:00:44
   ----- ---------------------------------- 13.4/102.4 MB 2.1 MB/s eta 0:00:44
   ----- ---------------------------------- 13.5/102.4 MB 2.0 MB/s eta 0:00:44
   ----- ---------------------------------- 13.5/102.4 MB 2.1 MB/s eta 0:00:44
   ----- ---------------------------------- 13.6/102.4 MB 2.0 MB/s eta 0:00:44
   ----- ---------------------------------- 13.7/102.4 MB 2.1 MB/s eta 0:00:44
   ----- ---------------------------------- 13.8/102.4 MB 2.0 MB/s eta 0:00:44
   ----- ---------------------------------- 13.9/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 14.0/102.4 MB 2.0 MB/s eta 0:00:44
   ----- ---------------------------------- 14.2/102.4 MB 2.1 MB/s eta 0:00:44
   ----- ---------------------------------- 14.2/102.4 MB 2.0 MB/s eta 0:00:44
   ----- ---------------------------------- 14.3/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 14.4/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 14.5/102.4 MB 2.0 MB/s eta 0:00:43
   ----- ---------------------------------- 14.6/102.4 MB 2.0 MB/s eta 0:00:43
   ----- ---------------------------------- 14.7/102.4 MB 2.0 MB/s eta 0:00:43
   ----- ---------------------------------- 14.8/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 14.9/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 15.0/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 15.2/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 15.2/102.4 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 15.3/102.4 MB 2.1 MB/s eta 0:00:43
   ------ --------------------------------- 15.5/102.4 MB 2.0 MB/s eta 0:00:43
   ------ --------------------------------- 15.6/102.4 MB 2.1 MB/s eta 0:00:43
   ------ --------------------------------- 15.7/102.4 MB 2.1 MB/s eta 0:00:43
   ------ --------------------------------- 15.8/102.4 MB 2.1 MB/s eta 0:00:43
   ------ --------------------------------- 15.9/102.4 MB 2.0 MB/s eta 0:00:43
   ------ --------------------------------- 16.0/102.4 MB 2.1 MB/s eta 0:00:43
   ------ --------------------------------- 16.1/102.4 MB 2.1 MB/s eta 0:00:43
   ------ --------------------------------- 16.2/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 16.3/102.4 MB 2.0 MB/s eta 0:00:43
   ------ --------------------------------- 16.4/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 16.5/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 16.7/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 16.8/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 16.9/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 17.0/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 17.1/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 17.2/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 17.3/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 17.4/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 17.5/102.4 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 17.6/102.4 MB 2.0 MB/s eta 0:00:42
   ------ --------------------------------- 17.7/102.4 MB 2.0 MB/s eta 0:00:42
   ------ --------------------------------- 17.7/102.4 MB 2.0 MB/s eta 0:00:42
   ------ --------------------------------- 17.8/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.0/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.1/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.1/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.2/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.4/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.4/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.6/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.7/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.7/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 18.9/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 19.0/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 19.0/102.4 MB 2.0 MB/s eta 0:00:42
   ------- -------------------------------- 19.2/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 19.3/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 19.4/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 19.5/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 19.6/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 19.7/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 19.8/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 19.9/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 20.0/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 20.1/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 20.2/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 20.3/102.4 MB 2.0 MB/s eta 0:00:41
   ------- -------------------------------- 20.4/102.4 MB 2.0 MB/s eta 0:00:41
   -------- ------------------------------- 20.5/102.4 MB 2.0 MB/s eta 0:00:41
   -------- ------------------------------- 20.6/102.4 MB 2.0 MB/s eta 0:00:41
   -------- ------------------------------- 20.7/102.4 MB 2.0 MB/s eta 0:00:41
   -------- ------------------------------- 20.8/102.4 MB 2.0 MB/s eta 0:00:41
   -------- ------------------------------- 20.9/102.4 MB 2.0 MB/s eta 0:00:41
   -------- ------------------------------- 20.9/102.4 MB 2.0 MB/s eta 0:00:41
   -------- ------------------------------- 20.9/102.4 MB 2.0 MB/s eta 0:00:41

In [19]:
!pip install moviepy

Requirement already satisfied: moviepy in c:\users\dell\anaconda3\lib\site-packages (2.2.1)
Requirement already satisfied: decorator<6.0,>=4.0.2 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (5.1.1)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (2.33.1)
Requirement already satisfied: imageio_ffmpeg>=0.2.0 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (0.6.0)
Requirement already satisfied: numpy>=1.25.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from moviepy) (1.26.4)
Requirement already satisfied: proglog<=1.0.0 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (0.1.12)
Requirement already satisfied: python-dotenv>=0.10 in c:\users\dell\anaconda3\lib\site-packages (from moviepy) (0.21.0)
Requirement already satisfied: pillow<12.0,>=9.2.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from moviepy) (11.3.0)
Requirement already satisfied: tqdm in c:\users\dell\appdata\roaming\python\python312\site-packages (from proglog<=1.0.0->moviepy) (4.67.1)
Requirement already satisfied: colorama in c:\users\dell\appdata\roaming\python\python312\site-packages (from tqdm->proglog<=1.0.0->moviepy) (0.4.6)

In [7]:
import os
import librosa
import numpy as np
import pandas as pd
import joblib
import subprocess

def extract_audio_ffmpeg(video_path, audio_path="temp_audio.mp3"):
    command = [
        "ffmpeg",
        "-i", video_path,   # مسار الفيديو
        "-vn",              # تجاهل الفيديو
        "-acodec", "mp3",  # صيغة WAV
        "-ar", "44100",     # sample rate
        "-ac", "1",         # mono
        audio_path
    ]
    subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
    return audio_path

def predict_scores_from_video_ffmpeg(video_path):
    model_path = r"C:/Users/DELL/Downloads/Graduation_project/xgboost_model.pkl"

    # استخراج الصوت
    audio_path = extract_audio_ffmpeg(video_path)

    # قراءة الصوت واستخراج MFCC
    y, sr = librosa.load(audio_path, sr=None)
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    mfcc_mean = np.mean(mfcc, axis=1)

    X = pd.DataFrame([mfcc_mean])
    #X.columns = [f"mfcc_{i+1}" for i in range(X.shape[1])]

    model = joblib.load(model_path)
    y_pred = model.predict(X)

    results = {
        "speech_rate_score": y_pred[0][0],
        "energy_score": y_pred[0][1],
        "confidence_score": y_pred[0][2],
        "pitch_mean": y_pred[0][3],
        "pitch_std": y_pred[0][4],
    }

   
    os.remove(audio_path)

    return results

In [13]:
path=r"C:\Users\DELL\Downloads\Sozy pleading.mp4"
predict_scores_from_video_ffmpeg(path)

FileNotFoundError: [WinError 2] The system cannot find the file specified

In [5]:
pip install "numpy<2"

Collecting numpy<2
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3
Successfully installed numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\~=mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\~=mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tensorflow 2.19.0 requires tensorboard~=2.19.0, but you have tensorboard 2.20.0 which is incompatible.
category-encoders 2.7.0 requires scikit-learn<1.6.0,>=1.0.0, but you have scikit-learn 1.8.0 which is incompatible.
facenet-pytorch 2.6.0 requires Pillow<10.3.0,>=10.2.0, but you have pillow 10.4.0 which is incompatible.
facenet-pytorch 2.6.0 requires torch<2.3.0,>=2.2.0, but you have torch 2.11.0 which is incompatible.
mediapipe 0.10.21 requires protobuf<5,>=4.25.3, but you have protobuf 5.29.5 which is incompatible.
mlxtend 0.24.0 requires numpy>=2.3.5, but you have numpy 1.26.4 which is incompatible.
pycaret 3.3.2 requires joblib<1.4,>=1.2.0, but you have joblib 1.5.3 which is incompatible.
pycaret 3.3.2 requires matplotlib<3.8.0, but you have matplotlib 3.10.8 which is incompatible.
pycaret 3.3.2 requires pandas<2.2.0, but you have pandas 2.3.3 which is incompatible.
pycaret 3.3.2 requires scipy<=1.11.4,>=1.6.1, but you have scipy 1.16.3 which is incompatible.
sktime 0.26.0 requires pandas<2.2.0,>=1.1, but you have pandas 2.3.3 which is incompatible.
sktime 0.26.0 requires scikit-learn<1.5.0,>=0.24, but you have scikit-learn 1.8.0 which is incompatible.
torchvision 0.17.2 requires torch==2.2.2, but you have torch 2.11.0 which is incompatible.

In [11]:
conda install -c conda-forge ffmpeg

error: incomplete escape \U at position 28