In [1]:
import mediapipe as mp

In [4]:
import cv2
import os

videos_folder = r"C:\Users\DELL\Downloads\EDITED vid"
output_base = r"C:\Users\DELL\Downloads\Extracted_Frames"

def extract_frames(video_path, output_folder, interval=2):
    os.makedirs(output_folder, exist_ok=True)
    cap = cv2.VideoCapture(video_path)
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    count, frame_id = 0, 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if count % (fps * interval) == 0:
            frame_path = os.path.join(output_folder, f"frame_{frame_id}.jpg")
            cv2.imwrite(frame_path, frame)
            frame_id += 1
        count += 1

    cap.release()
    print(f" Extracted {frame_id} frames from {video_path}")



for file in os.listdir(videos_folder):
    if file.lower().endswith(('.mp4', '.mov', '.avi', '.mkv')):
        video_path = os.path.join(videos_folder, file)

        video_name = os.path.splitext(file)[0]
        output_folder = os.path.join(output_base, video_name)

        print(f" Processing: {file}")
        extract_frames(video_path, output_folder, interval=2)

 Processing: V1.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V1.mp4
 Processing: V10.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V10.mp4
 Processing: V100.mp4
 Extracted 56 frames from C:\Users\DELL\Downloads\EDITED vid\V100.mp4
 Processing: V101.mp4
 Extracted 72 frames from C:\Users\DELL\Downloads\EDITED vid\V101.mp4
 Processing: V102.mp4
 Extracted 30 frames from C:\Users\DELL\Downloads\EDITED vid\V102.mp4
 Processing: V103.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V103.mp4
 Processing: V104.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V104.mp4
 Processing: V105.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V105.mp4
 Processing: V106.mp4
 Extracted 55 frames from C:\Users\DELL\Downloads\EDITED vid\V106.mp4
 Processing: V107.mp4
 Extracted 27 frames from C:\Users\DELL\Downloads\EDITED vid\V107.mp4
 Processing: V108.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V108.mp4
 Processing: V109.mp4
 Extracted 161 frames from C:\Users\DELL\Downloads\EDITED vid\V109.mp4
 Processing: V11.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V11.mp4
 Processing: V110.mp4
 Extracted 121 frames from C:\Users\DELL\Downloads\EDITED vid\V110.mp4
 Processing: V111.mp4
 Extracted 99 frames from C:\Users\DELL\Downloads\EDITED vid\V111.mp4
 Processing: V112.mp4
 Extracted 111 frames from C:\Users\DELL\Downloads\EDITED vid\V112.mp4
 Processing: V113.mp4
 Extracted 94 frames from C:\Users\DELL\Downloads\EDITED vid\V113.mp4
 Processing: V12.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V12.mp4
 Processing: V13.mp4
 Extracted 88 frames from C:\Users\DELL\Downloads\EDITED vid\V13.mp4
 Processing: V14.mp4
 Extracted 86 frames from C:\Users\DELL\Downloads\EDITED vid\V14.mp4
 Processing: V15.mp4
 Extracted 91 frames from C:\Users\DELL\Downloads\EDITED vid\V15.mp4
 Processing: V16.mp4
 Extracted 62 frames from C:\Users\DELL\Downloads\EDITED vid\V16.mp4
 Processing: V17.mp4
 Extracted 160 frames from C:\Users\DELL\Downloads\EDITED vid\V17.mp4
 Processing: V18.mp4
 Extracted 91 frames from C:\Users\DELL\Downloads\EDITED vid\V18.mp4
 Processing: V19.mp4
 Extracted 16 frames from C:\Users\DELL\Downloads\EDITED vid\V19.mp4
 Processing: V2.mp4
 Extracted 85 frames from C:\Users\DELL\Downloads\EDITED vid\V2.mp4
 Processing: V20.mp4
 Extracted 121 frames from C:\Users\DELL\Downloads\EDITED vid\V20.mp4
 Processing: V21.mp4
 Extracted 91 frames from C:\Users\DELL\Downloads\EDITED vid\V21.mp4
 Processing: V22.mp4
 Extracted 94 frames from C:\Users\DELL\Downloads\EDITED vid\V22.mp4
 Processing: v23.mp4
 Extracted 41 frames from C:\Users\DELL\Downloads\EDITED vid\v23.mp4
 Processing: v24.mp4
 Extracted 71 frames from C:\Users\DELL\Downloads\EDITED vid\v24.mp4
 Processing: V25.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V25.mp4
 Processing: V26.mp4
 Extracted 136 frames from C:\Users\DELL\Downloads\EDITED vid\V26.mp4
 Processing: V27.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V27.mp4
 Processing: v28.mp4
 Extracted 133 frames from C:\Users\DELL\Downloads\EDITED vid\v28.mp4
 Processing: V29.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V29.mp4
 Processing: V3.mp4
 Extracted 86 frames from C:\Users\DELL\Downloads\EDITED vid\V3.mp4
 Processing: V30.mp4
 Extracted 139 frames from C:\Users\DELL\Downloads\EDITED vid\V30.mp4
 Processing: V31.mp4
 Extracted 121 frames from C:\Users\DELL\Downloads\EDITED vid\V31.mp4
 Processing: V32.mp4
 Extracted 156 frames from C:\Users\DELL\Downloads\EDITED vid\V32.mp4
 Processing: V33.mp4
 Extracted 156 frames from C:\Users\DELL\Downloads\EDITED vid\V33.mp4
 Processing: V34.mp4
 Extracted 91 frames from C:\Users\DELL\Downloads\EDITED vid\V34.mp4
 Processing: V35.mp4
 Extracted 125 frames from C:\Users\DELL\Downloads\EDITED vid\V35.mp4
 Processing: V36.mp4
 Extracted 94 frames from C:\Users\DELL\Downloads\EDITED vid\V36.mp4
 Processing: v37.mp4
 Extracted 101 frames from C:\Users\DELL\Downloads\EDITED vid\v37.mp4
 Processing: V38.mp4
 Extracted 125 frames from C:\Users\DELL\Downloads\EDITED vid\V38.mp4
 Processing: V39.mp4
 Extracted 75 frames from C:\Users\DELL\Downloads\EDITED vid\V39.mp4
 Processing: V4.mp4
 Extracted 158 frames from C:\Users\DELL\Downloads\EDITED vid\V4.mp4
 Processing: V40.mp4
 Extracted 129 frames from C:\Users\DELL\Downloads\EDITED vid\V40.mp4
 Processing: V41.mp4
 Extracted 91 frames from C:\Users\DELL\Downloads\EDITED vid\V41.mp4
 Processing: V42.mp4
 Extracted 117 frames from C:\Users\DELL\Downloads\EDITED vid\V42.mp4
 Processing: V43.mp4
 Extracted 156 frames from C:\Users\DELL\Downloads\EDITED vid\V43.mp4
 Processing: v44.mp4
 Extracted 139 frames from C:\Users\DELL\Downloads\EDITED vid\v44.mp4
 Processing: V45.mp4
 Extracted 136 frames from C:\Users\DELL\Downloads\EDITED vid\V45.mp4
 Processing: V46.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V46.mp4
 Processing: V47.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V47.mp4
 Processing: V48.mp4
 Extracted 91 frames from C:\Users\DELL\Downloads\EDITED vid\V48.mp4
 Processing: V49.mp4
 Extracted 86 frames from C:\Users\DELL\Downloads\EDITED vid\V49.mp4
 Processing: V5.mp4
 Extracted 108 frames from C:\Users\DELL\Downloads\EDITED vid\V5.mp4
 Processing: V50.mp4
 Extracted 80 frames from C:\Users\DELL\Downloads\EDITED vid\V50.mp4
 Processing: V51.mp4
 Extracted 150 frames from C:\Users\DELL\Downloads\EDITED vid\V51.mp4
 Processing: V52.mp4
 Extracted 49 frames from C:\Users\DELL\Downloads\EDITED vid\V52.mp4
 Processing: V53.mp4
 Extracted 35 frames from C:\Users\DELL\Downloads\EDITED vid\V53.mp4
 Processing: V54.mp4
 Extracted 101 frames from C:\Users\DELL\Downloads\EDITED vid\V54.mp4
 Processing: V55.mp4
 Extracted 36 frames from C:\Users\DELL\Downloads\EDITED vid\V55.mp4
 Processing: V56.mp4
 Extracted 30 frames from C:\Users\DELL\Downloads\EDITED vid\V56.mp4
 Processing: V57.mp4
 Extracted 44 frames from C:\Users\DELL\Downloads\EDITED vid\V57.mp4
 Processing: V58.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V58.mp4
 Processing: V59.mp4
 Extracted 55 frames from C:\Users\DELL\Downloads\EDITED vid\V59.mp4
 Processing: V6.mp4
 Extracted 150 frames from C:\Users\DELL\Downloads\EDITED vid\V6.mp4
 Processing: V60.mp4
 Extracted 88 frames from C:\Users\DELL\Downloads\EDITED vid\V60.mp4
 Processing: V61.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V61.mp4
 Processing: V62.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V62.mp4
 Processing: V63.mp4
 Extracted 76 frames from C:\Users\DELL\Downloads\EDITED vid\V63.mp4
 Processing: V64.mp4
 Extracted 55 frames from C:\Users\DELL\Downloads\EDITED vid\V64.mp4
 Processing: V65.mp4
 Extracted 150 frames from C:\Users\DELL\Downloads\EDITED vid\V65.mp4
 Processing: V66.mp4
 Extracted 74 frames from C:\Users\DELL\Downloads\EDITED vid\V66.mp4
 Processing: V67.mp4
 Extracted 43 frames from C:\Users\DELL\Downloads\EDITED vid\V67.mp4
 Processing: V68.mp4
 Extracted 94 frames from C:\Users\DELL\Downloads\EDITED vid\V68.mp4
 Processing: V69.mp4
 Extracted 126 frames from C:\Users\DELL\Downloads\EDITED vid\V69.mp4
 Processing: V7.mp4
 Extracted 83 frames from C:\Users\DELL\Downloads\EDITED vid\V7.mp4
 Processing: V70.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V70.mp4
 Processing: V71.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V71.mp4
 Processing: V72.mp4
 Extracted 132 frames from C:\Users\DELL\Downloads\EDITED vid\V72.mp4
 Processing: V73.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V73.mp4
 Processing: V74.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V74.mp4
 Processing: V75.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V75.mp4
 Processing: V76.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V76.mp4
 Processing: V77.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V77.mp4
 Processing: V78.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V78.mp4
 Processing: V79.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V79.mp4
 Processing: V8.mp4
 Extracted 92 frames from C:\Users\DELL\Downloads\EDITED vid\V8.mp4
 Processing: V80.mp4
 Extracted 150 frames from C:\Users\DELL\Downloads\EDITED vid\V80.mp4
 Processing: V81.mp4
 Extracted 156 frames from C:\Users\DELL\Downloads\EDITED vid\V81.mp4
 Processing: V82.mp4
 Extracted 155 frames from C:\Users\DELL\Downloads\EDITED vid\V82.mp4
 Processing: V83.mp4
 Extracted 150 frames from C:\Users\DELL\Downloads\EDITED vid\V83.mp4
 Processing: V84.mp4
 Extracted 107 frames from C:\Users\DELL\Downloads\EDITED vid\V84.mp4
 Processing: V85.mp4
 Extracted 73 frames from C:\Users\DELL\Downloads\EDITED vid\V85.mp4
 Processing: V86.mp4
 Extracted 125 frames from C:\Users\DELL\Downloads\EDITED vid\V86.mp4
 Processing: V87.mp4
 Extracted 91 frames from C:\Users\DELL\Downloads\EDITED vid\V87.mp4
 Processing: V88.mp4
 Extracted 23 frames from C:\Users\DELL\Downloads\EDITED vid\V88.mp4
 Processing: V89.mp4
 Extracted 104 frames from C:\Users\DELL\Downloads\EDITED vid\V89.mp4
 Processing: V9.mp4
 Extracted 35 frames from C:\Users\DELL\Downloads\EDITED vid\V9.mp4
 Processing: V90.mp4
 Extracted 25 frames from C:\Users\DELL\Downloads\EDITED vid\V90.mp4
 Processing: V91.mp4
 Extracted 24 frames from C:\Users\DELL\Downloads\EDITED vid\V91.mp4
 Processing: V92.mp4
 Extracted 155 frames from C:\Users\DELL\Downloads\EDITED vid\V92.mp4
 Processing: V93.mp4
 Extracted 39 frames from C:\Users\DELL\Downloads\EDITED vid\V93.mp4
 Processing: V94.mp4
 Extracted 74 frames from C:\Users\DELL\Downloads\EDITED vid\V94.mp4
 Processing: V95.mp4
 Extracted 167 frames from C:\Users\DELL\Downloads\EDITED vid\V95.mp4
 Processing: V96.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V96.mp4
 Processing: V97.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V97.mp4
 Processing: V98.mp4
 Extracted 151 frames from C:\Users\DELL\Downloads\EDITED vid\V98.mp4
 Processing: V99.mp4
 Extracted 23 frames from C:\Users\DELL\Downloads\EDITED vid\V99.mp4

In [7]:
from fer.fer import FER
import cv2
import os
import pandas as pd
import numpy as np


def analyze_video_frames(video_frames_folder):
    detector = FER(mtcnn=True)
    rows = []

    for frame_file in sorted(os.listdir(video_frames_folder)):
        if frame_file.lower().endswith((".jpg", ".png", ".jpeg")):
            frame_path = os.path.join(video_frames_folder, frame_file)

            img = cv2.imread(frame_path)
            emotions = detector.detect_emotions(img)

            if emotions:
                probs = emotions[0]["emotions"]
                dominant = max(probs, key=probs.get)

                row = {"frame": frame_file, "dominant_emotion": dominant}
                row.update(probs)
                rows.append(row)

    # لو مفيش ولا وش ظهر
    if len(rows) == 0:
        return None

    df = pd.DataFrame(rows)

 
    summary = {}

    # mean لكل emotion
    emotion_cols = ["angry", "disgust", "fear", "happy", "sad", "surprise", "neutral"]
    for col in emotion_cols:
        summary[f"{col}_mean"] = df[col].mean()

    # dominant distribution
    dominant_counts = df["dominant_emotion"].value_counts(normalize=True)

    for emo in emotion_cols:
        summary[f"dominant_{emo}_percent"] = dominant_counts.get(emo, 0)

    return summary


base_folder = r"C:\Users\DELL\Downloads\Extracted_Frames"

final_results = []

for video_folder in os.listdir(base_folder):
    video_path = os.path.join(base_folder, video_folder)

    if os.path.isdir(video_path):
        print(f" Processing {video_folder} ...")

        summary = analyze_video_frames(video_path)

        if summary is not None:
            summary["video_name"] = video_folder
            final_results.append(summary)


final_df = pd.DataFrame(final_results)
output_excel = os.path.join(base_folder, "FER_summary_all_videos.xlsx")
final_df.to_excel(output_excel, index=False)

print("\n Done! Summary saved in:")
print(output_excel)

 Processing V1 ...

C:\Users\DELL\anaconda3\envs\body\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\DELL\anaconda3\envs\body\lib\site-packages\tensorflow\lite\python\interpreter.py:457: UserWarning:     Warning: tf.lite.Interpreter is deprecated and is scheduled for deletion in
    TF 2.20. Please use the LiteRT interpreter from the ai_edge_litert package.
    See the [migration guide](https://ai.google.dev/edge/litert/migration)
    for details.

  warnings.warn(_INTERPRETER_DELETION_WARNING)

 Processing V10 ...
 Processing V100 ...
 Processing V101 ...
 Processing V102 ...
 Processing V103 ...
 Processing V104 ...
 Processing V105 ...
 Processing V106 ...
 Processing V107 ...
 Processing V108 ...
 Processing V109 ...
 Processing V11 ...
 Processing V110 ...
 Processing V111 ...
 Processing V112 ...
 Processing V113 ...
 Processing V12 ...
 Processing V13 ...
 Processing V14 ...
 Processing V15 ...
 Processing V16 ...
 Processing V17 ...
 Processing V18 ...
 Processing V19 ...
 Processing V2 ...
 Processing V20 ...
 Processing V21 ...
 Processing V22 ...
 Processing v23 ...
 Processing v24 ...
 Processing V25 ...
 Processing V26 ...
 Processing V27 ...
 Processing v28 ...
 Processing V29 ...
 Processing V3 ...
 Processing V30 ...
 Processing V31 ...
 Processing V32 ...
 Processing V33 ...
 Processing V34 ...
 Processing V35 ...
 Processing V36 ...
 Processing v37 ...
 Processing V38 ...
 Processing V39 ...
 Processing V4 ...
 Processing V40 ...
 Processing V41 ...
 Processing V42 ...
 Processing V43 ...
 Processing v44 ...
 Processing V45 ...
 Processing V46 ...
 Processing V47 ...
 Processing V48 ...
 Processing V49 ...
 Processing V5 ...
 Processing V50 ...
 Processing V51 ...
 Processing V52 ...
 Processing V53 ...
 Processing V54 ...
 Processing V55 ...
 Processing V56 ...
 Processing V57 ...
 Processing V58 ...
 Processing V59 ...
 Processing V6 ...
 Processing V60 ...
 Processing V61 ...
 Processing V62 ...
 Processing V63 ...
 Processing V64 ...
 Processing V65 ...
 Processing V66 ...
 Processing V67 ...
 Processing V68 ...
 Processing V69 ...
 Processing V7 ...
 Processing V70 ...
 Processing V71 ...
 Processing V72 ...
 Processing V73 ...
 Processing V74 ...
 Processing V75 ...
 Processing V76 ...
 Processing V77 ...
 Processing V78 ...
 Processing V79 ...
 Processing V8 ...
 Processing V80 ...
 Processing V81 ...
 Processing V82 ...
 Processing V83 ...
 Processing V84 ...
 Processing V85 ...
 Processing V86 ...
 Processing V87 ...
 Processing V88 ...
 Processing V89 ...
 Processing V9 ...
 Processing V90 ...
 Processing V91 ...
 Processing V92 ...
 Processing V93 ...
 Processing V94 ...
 Processing V95 ...
 Processing V96 ...
 Processing V97 ...
 Processing V98 ...
 Processing V99 ...

ModuleNotFoundError: No module named 'openpyxl'

In [8]:
final_df

,angry_mean,disgust_mean,fear_mean,happy_mean,sad_mean,surprise_mean,neutral_mean,dominant_angry_percent,dominant_disgust_percent,dominant_fear_percent,dominant_happy_percent,dominant_sad_percent,dominant_surprise_percent,dominant_neutral_percent,video_name
0,0.265929,0.001150,0.085487,0.098496,0.179204,0.037257,0.331416,0.238938,0.0,0.017699,0.088496,0.185841,0.026549,0.442478,V1
1,0.278133,0.001733,0.118933,0.182733,0.179267,0.022867,0.215200,0.353333,0.0,0.046667,0.193333,0.173333,0.006667,0.226667,V10
2,0.186909,0.000182,0.107636,0.086364,0.334000,0.011273,0.273818,0.109091,0.0,0.000000,0.054545,0.490909,0.000000,0.345455,V100
3,0.228889,0.000222,0.096444,0.174444,0.123556,0.145111,0.231111,0.333333,0.0,0.044444,0.177778,0.044444,0.088889,0.311111,V101
4,0.269310,0.000690,0.098966,0.041724,0.127586,0.012414,0.446552,0.241379,0.0,0.068966,0.034483,0.034483,0.000000,0.620690,V102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,0.289091,0.000364,0.124545,0.125818,0.222909,0.049455,0.187091,0.436364,0.0,0.018182,0.145455,0.218182,0.018182,0.163636,V95
109,0.177467,0.000867,0.179600,0.037667,0.117133,0.120333,0.365600,0.153333,0.0,0.080000,0.013333,0.093333,0.120000,0.540000,V96
110,0.206358,0.000927,0.156954,0.037682,0.179404,0.095232,0.322185,0.192053,0.0,0.079470,0.026490,0.218543,0.112583,0.370861,V97
111,0.220331,0.002384,0.160993,0.039470,0.208609,0.097550,0.269470,0.211921,0.0,0.105960,0.019868,0.245033,0.099338,0.317881,V98
112,0.173333,0.001429,0.099524,0.154762,0.288571,0.022381,0.258095,0.142857,0.0,0.000000,0.238095,0.523810,0.000000,0.095238,V99

In [10]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [11]:
output_excel = os.path.join(base_folder, "FER_summary_all_videos.xlsx")
final_df.to_excel(output_excel, index=False)
print(output_excel)

C:\Users\DELL\Downloads\Extracted_Frames\FER_summary_all_videos.xlsx

In [1]:
import os
import cv2
import mediapipe as mp
import pandas as pd
import numpy as np

def analyze_body_folder(frame_folder):
    mp_pose = mp.solutions.pose

    # تشغيل MediaPipe بصيغة with علشان يتقفل لوحده
    with mp_pose.Pose(static_image_mode=True) as pose:

        rows = []

        for frame_file in sorted(os.listdir(frame_folder)):
            frame_path = os.path.join(frame_folder, frame_file)
            if not frame_file.lower().endswith((".jpg", ".png")):
                continue

            img = cv2.imread(frame_path)
            if img is None:
                continue

            # ↓↓↓ تصغير الصورة علشان ما تضربيش OutOfMemory
            img = cv2.resize(img, None, fx=0.3, fy=0.3)

            # تشغيل MediaPipe
            result = pose.process(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

            if result.pose_landmarks:
                lm = result.pose_landmarks.landmark
                row = {}
                for i in range(len(lm)):
                    row[f"lm_{i}_x"] = lm[i].x
                    row[f"lm_{i}_y"] = lm[i].y
                    row[f"lm_{i}_z"] = lm[i].z
                rows.append(row)

            # مسح الصورة من الذاكرة
            del img

    # مفيش landmarks؟ رجّعي None
    if len(rows) == 0:
        return None

    df = pd.DataFrame(rows)
    mean_row = df.mean(numeric_only=True)
    return mean_row



def analyze_all_videos(base_folder):
    """
    base_folder = فولدر Extracted_Frames اللي جواه فولدر لكل فيديو
    """
    final_results = []

    for video_folder in os.listdir(base_folder):
        video_path = os.path.join(base_folder, video_folder)

        if not os.path.isdir(video_path):
            continue

        print(f" Analyzing body posture for video: {video_folder}")

        result = analyze_body_folder(video_path)

        if result is not None:
            result = result.to_dict()
            result["video_name"] = video_folder
            final_results.append(result)
            print(f" Done: {video_folder}")
        else:
            print(f" No body detected in: {video_folder}")

    # حفظهم في Excel واحد
    final_df2 = pd.DataFrame(final_results)

    output_excel2 = os.path.join(base_folder, "Mediapipe_Body_Summary.xlsx")
    final_df2.to_excel(output_excel2, index=False)

    print("\n All videos processed successfully!")
    print(" Output saved at:", output_excel2)



base_folder = r"C:\Users\DELL\Downloads\Extracted_Frames"
analyze_all_videos(base_folder)

 Analyzing body posture for video: V1

C:\Users\DELL\anaconda3\envs\body\lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '

 Done: V1
 Analyzing body posture for video: V10
 Done: V10
 Analyzing body posture for video: V100
 Done: V100
 Analyzing body posture for video: V101
 Done: V101
 Analyzing body posture for video: V102
 Done: V102
 Analyzing body posture for video: V103
 Done: V103
 Analyzing body posture for video: V104
 Done: V104
 Analyzing body posture for video: V105
 Done: V105
 Analyzing body posture for video: V106
 Done: V106
 Analyzing body posture for video: V107
 Done: V107
 Analyzing body posture for video: V108
 Done: V108
 Analyzing body posture for video: V109
 Done: V109
 Analyzing body posture for video: V11
 Done: V11
 Analyzing body posture for video: V110
 Done: V110
 Analyzing body posture for video: V111
 Done: V111
 Analyzing body posture for video: V112
 Done: V112
 Analyzing body posture for video: V113
 Done: V113
 Analyzing body posture for video: V12
 Done: V12
 Analyzing body posture for video: V13
 Done: V13
 Analyzing body posture for video: V14
 Done: V14
 Analyzing body posture for video: V15
 Done: V15
 Analyzing body posture for video: V16
 Done: V16
 Analyzing body posture for video: V17
 Done: V17
 Analyzing body posture for video: V18
 Done: V18
 Analyzing body posture for video: V19
 Done: V19
 Analyzing body posture for video: V2
 Done: V2
 Analyzing body posture for video: V20
 Done: V20
 Analyzing body posture for video: V21
 Done: V21
 Analyzing body posture for video: V22
 Done: V22
 Analyzing body posture for video: v23
 Done: v23
 Analyzing body posture for video: v24
 Done: v24
 Analyzing body posture for video: V25
 Done: V25
 Analyzing body posture for video: V26
 Done: V26
 Analyzing body posture for video: V27
 Done: V27
 Analyzing body posture for video: v28
 Done: v28
 Analyzing body posture for video: V29
 Done: V29
 Analyzing body posture for video: V3
 Done: V3
 Analyzing body posture for video: V30
 Done: V30
 Analyzing body posture for video: V31
 Done: V31
 Analyzing body posture for video: V32
 Done: V32
 Analyzing body posture for video: V33
 Done: V33
 Analyzing body posture for video: V34
 Done: V34
 Analyzing body posture for video: V35
 Done: V35
 Analyzing body posture for video: V36
 Done: V36
 Analyzing body posture for video: v37
 Done: v37
 Analyzing body posture for video: V38
 Done: V38
 Analyzing body posture for video: V39
 Done: V39
 Analyzing body posture for video: V4
 Done: V4
 Analyzing body posture for video: V40
 Done: V40
 Analyzing body posture for video: V41
 Done: V41
 Analyzing body posture for video: V42
 Done: V42
 Analyzing body posture for video: V43
 Done: V43
 Analyzing body posture for video: v44
 Done: v44
 Analyzing body posture for video: V45
 Done: V45
 Analyzing body posture for video: V46
 Done: V46
 Analyzing body posture for video: V47
 Done: V47
 Analyzing body posture for video: V48
 Done: V48
 Analyzing body posture for video: V49
 Done: V49
 Analyzing body posture for video: V5
 Done: V5
 Analyzing body posture for video: V50
 Done: V50
 Analyzing body posture for video: V51
 Done: V51
 Analyzing body posture for video: V52
 Done: V52
 Analyzing body posture for video: V53
 Done: V53
 Analyzing body posture for video: V54
 Done: V54
 Analyzing body posture for video: V55
 Done: V55
 Analyzing body posture for video: V56
 Done: V56
 Analyzing body posture for video: V57
 Done: V57
 Analyzing body posture for video: V58
 Done: V58
 Analyzing body posture for video: V59
 Done: V59
 Analyzing body posture for video: V6
 Done: V6
 Analyzing body posture for video: V60
 Done: V60
 Analyzing body posture for video: V61
 Done: V61
 Analyzing body posture for video: V62
 Done: V62
 Analyzing body posture for video: V63
 Done: V63
 Analyzing body posture for video: V64
 Done: V64
 Analyzing body posture for video: V65
 Done: V65
 Analyzing body posture for video: V66
 Done: V66
 Analyzing body posture for video: V67
 Done: V67
 Analyzing body posture for video: V68
 Done: V68
 Analyzing body posture for video: V69
 Done: V69
 Analyzing body posture for video: V7
 Done: V7
 Analyzing body posture for video: V70
 Done: V70
 Analyzing body posture for video: V71
 Done: V71
 Analyzing body posture for video: V72
 Done: V72
 Analyzing body posture for video: V73
 Done: V73
 Analyzing body posture for video: V74
 Done: V74
 Analyzing body posture for video: V75
 Done: V75
 Analyzing body posture for video: V76
 Done: V76
 Analyzing body posture for video: V77
 Done: V77
 Analyzing body posture for video: V78
 Done: V78
 Analyzing body posture for video: V79
 Done: V79
 Analyzing body posture for video: V8
 Done: V8
 Analyzing body posture for video: V80
 Done: V80
 Analyzing body posture for video: V81
 Done: V81
 Analyzing body posture for video: V82
 Done: V82
 Analyzing body posture for video: V83
 Done: V83
 Analyzing body posture for video: V84
 Done: V84
 Analyzing body posture for video: V85
 Done: V85
 Analyzing body posture for video: V86
 Done: V86
 Analyzing body posture for video: V87
 Done: V87
 Analyzing body posture for video: V88
 Done: V88
 Analyzing body posture for video: V89
 Done: V89
 Analyzing body posture for video: V9
 Done: V9
 Analyzing body posture for video: V90
 Done: V90
 Analyzing body posture for video: V91
 Done: V91
 Analyzing body posture for video: V92
 Done: V92
 Analyzing body posture for video: V93
 Done: V93
 Analyzing body posture for video: V94
 Done: V94
 Analyzing body posture for video: V95
 Done: V95
 Analyzing body posture for video: V96
 Done: V96
 Analyzing body posture for video: V97
 Done: V97
 Analyzing body posture for video: V98
 Done: V98
 Analyzing body posture for video: V99
 Done: V99

 All videos processed successfully!
 Output saved at: C:\Users\DELL\Downloads\Extracted_Frames\Mediapipe_Body_Summary.xlsx

In [21]:
import pandas as pd

df = pd.read_excel(r"C:\Users\DELL\Downloads\Graduation_project\Mediapipe_Body_Summary.xlsx")
df

,lm_0_x,lm_0_y,lm_0_z,lm_1_x,lm_1_y,lm_1_z,lm_2_x,lm_2_y,lm_2_z,lm_3_x,...,lm_30_x,lm_30_y,lm_30_z,lm_31_x,lm_31_y,lm_31_z,lm_32_x,lm_32_y,lm_32_z,video_name
0,0.395964,0.320213,-0.304125,0.399935,0.291850,-0.286200,0.403436,0.291100,-0.286258,0.406758,...,0.309604,1.248029,0.248177,0.394789,1.287029,0.133979,0.321427,1.298982,0.108637,V1
1,0.475478,0.451061,-0.302581,0.472125,0.439917,-0.270683,0.474452,0.439837,-0.270850,0.476478,...,0.452587,0.827916,0.248940,0.571283,0.824553,0.255346,0.509784,0.839911,0.116742,V10
2,0.425647,0.336448,-0.339998,0.452498,0.293331,-0.403559,0.464745,0.291107,-0.403744,0.478379,...,0.452951,1.543938,0.500823,0.413163,1.615071,-0.073288,0.315350,1.620061,0.324574,V100
3,0.591944,0.354361,-0.244775,0.610731,0.337655,-0.277808,0.620353,0.337093,-0.277926,0.630301,...,0.629237,0.897637,0.458047,0.597666,0.959741,-0.090383,0.521719,0.923245,0.357830,V101
4,0.497987,0.278717,-0.657157,0.518605,0.248287,-0.658612,0.529899,0.248934,-0.658689,0.543427,...,0.455322,1.076314,0.881497,0.531008,1.161149,0.740517,0.418814,1.160870,0.777224,V102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,0.560945,0.464964,0.059155,0.565049,0.437720,0.010781,0.565334,0.438014,0.010736,0.565601,...,0.609843,1.507161,0.472340,0.572419,1.461613,0.303179,0.574428,1.497179,0.413101,V95
109,0.517249,0.390280,-0.372441,0.513800,0.365101,-0.339061,0.516297,0.365526,-0.339182,0.518588,...,0.468881,1.713122,0.357667,0.575797,1.727447,0.261589,0.504036,1.750140,0.121649,V96
110,0.528884,0.419666,-0.366228,0.526618,0.392960,-0.333496,0.529047,0.393298,-0.333636,0.531293,...,0.479228,1.691582,0.309320,0.581700,1.704125,0.233836,0.515313,1.726884,0.082137,V97
111,0.524630,0.428309,-0.363920,0.523948,0.401170,-0.332783,0.526730,0.401500,-0.332913,0.529225,...,0.480134,1.682951,0.296360,0.580782,1.697791,0.221316,0.514254,1.720146,0.071483,V98
112,0.437460,0.380050,-0.297460,0.434127,0.367753,-0.272979,0.435119,0.367652,-0.273183,0.436277,...,0.325855,0.755402,0.178657,0.441503,0.737020,0.349192,0.383532,0.752514,0.058995,V99

In [9]:
import pandas as pd

df2 = pd.read_excel(r"C:/Users/DELL/Downloads\Graduation_project\FER_summary_all_videos.xlsx")
df2

,angry_mean,disgust_mean,fear_mean,happy_mean,sad_mean,surprise_mean,neutral_mean,dominant_angry_percent,dominant_disgust_percent,dominant_fear_percent,dominant_happy_percent,dominant_sad_percent,dominant_surprise_percent,dominant_neutral_percent,video_name
0,0.265929,0.001150,0.085487,0.098496,0.179204,0.037257,0.331416,0.238938,0.0,0.017699,0.088496,0.185841,0.026549,0.442478,V1
1,0.278133,0.001733,0.118933,0.182733,0.179267,0.022867,0.215200,0.353333,0.0,0.046667,0.193333,0.173333,0.006667,0.226667,V10
2,0.186909,0.000182,0.107636,0.086364,0.334000,0.011273,0.273818,0.109091,0.0,0.000000,0.054545,0.490909,0.000000,0.345455,V100
3,0.228889,0.000222,0.096444,0.174444,0.123556,0.145111,0.231111,0.333333,0.0,0.044444,0.177778,0.044444,0.088889,0.311111,V101
4,0.269310,0.000690,0.098966,0.041724,0.127586,0.012414,0.446552,0.241379,0.0,0.068966,0.034483,0.034483,0.000000,0.620690,V102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,0.289091,0.000364,0.124545,0.125818,0.222909,0.049455,0.187091,0.436364,0.0,0.018182,0.145455,0.218182,0.018182,0.163636,V95
109,0.177467,0.000867,0.179600,0.037667,0.117133,0.120333,0.365600,0.153333,0.0,0.080000,0.013333,0.093333,0.120000,0.540000,V96
110,0.206358,0.000927,0.156954,0.037682,0.179404,0.095232,0.322185,0.192053,0.0,0.079470,0.026490,0.218543,0.112583,0.370861,V97
111,0.220331,0.002384,0.160993,0.039470,0.208609,0.097550,0.269470,0.211921,0.0,0.105960,0.019868,0.245033,0.099338,0.317881,V98
112,0.173333,0.001429,0.099524,0.154762,0.288571,0.022381,0.258095,0.142857,0.0,0.000000,0.238095,0.523810,0.000000,0.095238,V99

In [11]:
import re

df2["video_no"] = df2["video_name"].apply(lambda x: int(re.search(r'\d+', x).group()) if re.search(r'\d+', x) else -1)


df2 = df2.sort_values(by="video_no").reset_index(drop=True)

df2 = df2.drop(columns=["video_no"])


output_path = r"C:\Users\DELL\Downloads\fer_sorted.xlsx"
df2.to_excel(output_path, index=False)

print(df2["video_name"])

0        V1
1        V2
2        V3
3        V4
4        V5
       ...
108    V109
109    V110
110    V111
111    V112
112    V113
Name: video_name, Length: 113, dtype: object

In [13]:
import re

df["video_no"] = df["video_name"].apply(lambda x: int(re.search(r'\d+', x).group()) if re.search(r'\d+', x) else -1)


df = df.sort_values(by="video_no").reset_index(drop=True)

df = df.drop(columns=["video_no"])


output_path = r"C:\Users\DELL\Downloads\body_language_sorted.xlsx"
df.to_excel(output_path, index=False)

print(df["video_name"])

0        V1
1        V2
2        V3
3        V4
4        V5
       ...
108    V109
109    V110
110    V111
111    V112
112    V113
Name: video_name, Length: 113, dtype: object

In [15]:
final_df = pd.merge(
    df,
    df2,
    on="video_name",
    how="inner"
)

In [17]:
final_df

,lm_0_x,lm_0_y,lm_0_z,lm_1_x,lm_1_y,lm_1_z,lm_2_x,lm_2_y,lm_2_z,lm_3_x,...,sad_mean,surprise_mean,neutral_mean,dominant_angry_percent,dominant_disgust_percent,dominant_fear_percent,dominant_happy_percent,dominant_sad_percent,dominant_surprise_percent,dominant_neutral_percent
0,0.395964,0.320213,-0.304125,0.399935,0.291850,-0.286200,0.403436,0.291100,-0.286258,0.406758,...,0.179204,0.037257,0.331416,0.238938,0.0,0.017699,0.088496,0.185841,0.026549,0.442478
1,0.383475,0.155170,-0.150292,0.384259,0.143362,-0.125967,0.387558,0.143213,-0.126137,0.392479,...,0.269625,0.025000,0.215125,0.112500,0.0,0.100000,0.162500,0.412500,0.012500,0.200000
2,0.384402,0.286855,-0.410269,0.385219,0.256718,-0.369905,0.389300,0.257127,-0.370063,0.393194,...,0.160122,0.101951,0.225244,0.158537,0.0,0.158537,0.219512,0.109756,0.097561,0.256098
3,0.341753,0.489156,-0.127466,0.337333,0.482715,-0.109281,0.337742,0.482798,-0.109392,0.338009,...,0.306489,0.040957,0.171064,0.223404,0.0,0.021277,0.212766,0.414894,0.021277,0.106383
4,0.541009,0.186289,-0.174473,0.527455,0.163063,-0.141196,0.527536,0.162719,-0.141512,0.527206,...,0.242500,0.011500,0.200000,0.700000,0.0,0.000000,0.050000,0.200000,0.000000,0.050000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,0.284816,0.317117,-0.863272,0.312612,0.291836,-0.809081,0.320804,0.293290,-0.809706,0.325148,...,0.226857,0.023143,0.270857,0.228571,0.0,0.000000,0.200000,0.257143,0.000000,0.314286
109,0.498405,0.336019,-0.476285,0.511188,0.320361,-0.456019,0.516909,0.322599,-0.456092,0.522592,...,0.340167,0.006833,0.149083,0.175000,0.0,0.025000,0.208333,0.466667,0.000000,0.125000
110,0.453668,0.276462,-0.051321,0.447577,0.260737,-0.042861,0.446975,0.260576,-0.042959,0.446272,...,0.298776,0.007959,0.089184,0.326531,0.0,0.020408,0.153061,0.428571,0.000000,0.071429
111,0.400403,0.328811,-0.348069,0.387171,0.292032,-0.325842,0.388248,0.289955,-0.326018,0.388892,...,0.199091,0.013636,0.417273,0.090909,0.0,0.000000,0.181818,0.136364,0.000000,0.590909
112,0.527650,0.421003,-0.400042,0.530669,0.402517,-0.365860,0.534967,0.402685,-0.366037,0.539179,...,0.173404,0.027234,0.236489,0.351064,0.0,0.021277,0.180851,0.170213,0.000000,0.276596

In [19]:
cols = ["video_name"] + [col for col in final_df.columns if col != "video_name"]
final_df = final_df[cols]

In [21]:
final_df

,video_name,lm_0_x,lm_0_y,lm_0_z,lm_1_x,lm_1_y,lm_1_z,lm_2_x,lm_2_y,lm_2_z,...,sad_mean,surprise_mean,neutral_mean,dominant_angry_percent,dominant_disgust_percent,dominant_fear_percent,dominant_happy_percent,dominant_sad_percent,dominant_surprise_percent,dominant_neutral_percent
0,V1,0.395964,0.320213,-0.304125,0.399935,0.291850,-0.286200,0.403436,0.291100,-0.286258,...,0.179204,0.037257,0.331416,0.238938,0.0,0.017699,0.088496,0.185841,0.026549,0.442478
1,V2,0.383475,0.155170,-0.150292,0.384259,0.143362,-0.125967,0.387558,0.143213,-0.126137,...,0.269625,0.025000,0.215125,0.112500,0.0,0.100000,0.162500,0.412500,0.012500,0.200000
2,V3,0.384402,0.286855,-0.410269,0.385219,0.256718,-0.369905,0.389300,0.257127,-0.370063,...,0.160122,0.101951,0.225244,0.158537,0.0,0.158537,0.219512,0.109756,0.097561,0.256098
3,V4,0.341753,0.489156,-0.127466,0.337333,0.482715,-0.109281,0.337742,0.482798,-0.109392,...,0.306489,0.040957,0.171064,0.223404,0.0,0.021277,0.212766,0.414894,0.021277,0.106383
4,V5,0.541009,0.186289,-0.174473,0.527455,0.163063,-0.141196,0.527536,0.162719,-0.141512,...,0.242500,0.011500,0.200000,0.700000,0.0,0.000000,0.050000,0.200000,0.000000,0.050000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,V109,0.284816,0.317117,-0.863272,0.312612,0.291836,-0.809081,0.320804,0.293290,-0.809706,...,0.226857,0.023143,0.270857,0.228571,0.0,0.000000,0.200000,0.257143,0.000000,0.314286
109,V110,0.498405,0.336019,-0.476285,0.511188,0.320361,-0.456019,0.516909,0.322599,-0.456092,...,0.340167,0.006833,0.149083,0.175000,0.0,0.025000,0.208333,0.466667,0.000000,0.125000
110,V111,0.453668,0.276462,-0.051321,0.447577,0.260737,-0.042861,0.446975,0.260576,-0.042959,...,0.298776,0.007959,0.089184,0.326531,0.0,0.020408,0.153061,0.428571,0.000000,0.071429
111,V112,0.400403,0.328811,-0.348069,0.387171,0.292032,-0.325842,0.388248,0.289955,-0.326018,...,0.199091,0.013636,0.417273,0.090909,0.0,0.000000,0.181818,0.136364,0.000000,0.590909
112,V113,0.527650,0.421003,-0.400042,0.530669,0.402517,-0.365860,0.534967,0.402685,-0.366037,...,0.173404,0.027234,0.236489,0.351064,0.0,0.021277,0.180851,0.170213,0.000000,0.276596

In [23]:
final_df.to_excel(
    r"C:\Users\DELL\Downloads\body_fer_dataset.xlsx",
    index=False
)

In [23]:
df.columns

Index(['lm_0_x', 'lm_0_y', 'lm_0_z', 'lm_1_x', 'lm_1_y', 'lm_1_z', 'lm_2_x',
       'lm_2_y', 'lm_2_z', 'lm_3_x', 'lm_3_y', 'lm_3_z', 'lm_4_x', 'lm_4_y',
       'lm_4_z', 'lm_5_x', 'lm_5_y', 'lm_5_z', 'lm_6_x', 'lm_6_y', 'lm_6_z',
       'lm_7_x', 'lm_7_y', 'lm_7_z', 'lm_8_x', 'lm_8_y', 'lm_8_z', 'lm_9_x',
       'lm_9_y', 'lm_9_z', 'lm_10_x', 'lm_10_y', 'lm_10_z', 'lm_11_x',
       'lm_11_y', 'lm_11_z', 'lm_12_x', 'lm_12_y', 'lm_12_z', 'lm_13_x',
       'lm_13_y', 'lm_13_z', 'lm_14_x', 'lm_14_y', 'lm_14_z', 'lm_15_x',
       'lm_15_y', 'lm_15_z', 'lm_16_x', 'lm_16_y', 'lm_16_z', 'lm_17_x',
       'lm_17_y', 'lm_17_z', 'lm_18_x', 'lm_18_y', 'lm_18_z', 'lm_19_x',
       'lm_19_y', 'lm_19_z', 'lm_20_x', 'lm_20_y', 'lm_20_z', 'lm_21_x',
       'lm_21_y', 'lm_21_z', 'lm_22_x', 'lm_22_y', 'lm_22_z', 'lm_23_x',
       'lm_23_y', 'lm_23_z', 'lm_24_x', 'lm_24_y', 'lm_24_z', 'lm_25_x',
       'lm_25_y', 'lm_25_z', 'lm_26_x', 'lm_26_y', 'lm_26_z', 'lm_27_x',
       'lm_27_y', 'lm_27_z', 'lm_28_x', 'lm_28_y', 'lm_28_z', 'lm_29_x',
       'lm_29_y', 'lm_29_z', 'lm_30_x', 'lm_30_y', 'lm_30_z', 'lm_31_x',
       'lm_31_y', 'lm_31_z', 'lm_32_x', 'lm_32_y', 'lm_32_z', 'video_name'],
      dtype='object')

In [27]:
df2.columns

Index(['angry_mean', 'disgust_mean', 'fear_mean', 'happy_mean', 'sad_mean',
       'surprise_mean', 'neutral_mean', 'dominant_angry_percent',
       'dominant_disgust_percent', 'dominant_fear_percent',
       'dominant_happy_percent', 'dominant_sad_percent',
       'dominant_surprise_percent', 'dominant_neutral_percent', 'video_name'],
      dtype='object')

In [29]:
import numpy as np
import pandas as pd


final_df["head_tilt"] = abs(final_df["lm_0_y"] - final_df["lm_1_y"])

final_df["head_stability_label"] = np.where(
    final_df["head_tilt"] < 0.08,
    "Stable Head",
    "Unstable Head"
)


final_df["shoulder_width"] = abs(final_df["lm_11_x"] - final_df["lm_12_x"])

final_df["posture_openness_label"] = np.where(
    final_df["shoulder_width"] > 0.15,
    "Open Posture",
    "Closed Posture"
)

final_df["body_stability_label"] = np.where(
    abs(final_df["lm_23_z"]) < 0.3,
    "Stable Body",
    "Unstable Body"
)

# =========================
# 🟢 BODY CONFIDENCE (نصي)
# =========================

def body_confidence(row):
    if (
        row["head_stability_label"] == "Stable Head" and
        row["posture_openness_label"] == "Open Posture" and
        row["body_stability_label"] == "Stable Body"
    ):
        return "High Body Confidence"

    if (
        row["posture_openness_label"] == "Closed Posture" and
        row["body_stability_label"] == "Unstable Body"
    ):
        return "Low Body Confidence"

    return "Moderate Body Confidence"


final_df.loc[:, "body_confidence_label"] = final_df.apply(body_confidence, axis=1)

# =========================
# 🟢 EMOTION ANALYSIS (FER)
# =========================

def emotion_state(row):
    if row["happy_mean"] > 0.4:
        return "Positive / Friendly"

    if row["sad_mean"] > 0.25 or row["fear_mean"] > 0.25:
        return "Anxious / Nervous"

    if row["angry_mean"] > 0.25:
        return "Aggressive / Defensive"

    return "Neutral / Controlled"

final_df["emotional_state_label"] = final_df.apply(emotion_state, axis=1)

# =========================
# 🟢 CONFIDENCE FROM EMOTIONS
# =========================

def emotional_confidence(row):
    if (
        row["dominant_happy_percent"] > 0.3 and
        row["dominant_neutral_percent"] > 0.2
    ):
        return "Emotionally Confident"

    if row["dominant_fear_percent"] > 0.25 or row["dominant_sad_percent"] > 0.3:
        return "Emotionally Insecure"

    return "Emotionally Balanced"

final_df["emotional_confidence_label"] = final_df.apply(emotional_confidence, axis=1)

# =========================
# 🟢 OVERALL CONFIDENCE
# =========================

def overall_confidence(row):
    if (
        row["body_confidence_label"] == "High Body Confidence" and
        row["emotional_confidence_label"] == "Emotionally Confident"
    ):
        return "Very Confident Speaker"

    if (
        row["body_confidence_label"] == "Low Body Confidence" and
        row["emotional_confidence_label"] == "Emotionally Insecure"
    ):
        return "Low Confidence Speaker"

    return "Moderately Confident Speaker"

final_df["overall_confidence_label"] = final_df.apply(overall_confidence, axis=1)

# =========================
# 🟢 ENGAGEMENT LEVEL
# =========================

def engagement(row):
    if row["dominant_happy_percent"] > 0.25 and row["open_posture"] if "open_posture" in row else True:
        return "Highly Engaged"

    if row["dominant_neutral_percent"] > 0.5:
        return "Moderately Engaged"

    return "Low Engagement"

final_df["engagement_label"] = final_df.apply(engagement, axis=1)

C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["head_tilt"] = abs(final_df["lm_0_y"] - final_df["lm_1_y"])
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["head_stability_label"] = np.where(
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["shoulder_width"] = abs(final_df["lm_11_x"] - final_df["lm_12_x"])
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["posture_openness_label"] = np.where(
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["body_stability_label"] = np.where(
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.loc[:, "body_confidence_label"] = final_df.apply(body_confidence, axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["emotional_state_label"] = final_df.apply(emotion_state, axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["emotional_confidence_label"] = final_df.apply(emotional_confidence, axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["overall_confidence_label"] = final_df.apply(overall_confidence, axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_10368\3446461897.py:129: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["engagement_label"] = final_df.apply(engagement, axis=1)

In [31]:
final_df

,video_name,lm_0_x,lm_0_y,lm_0_z,lm_1_x,lm_1_y,lm_1_z,lm_2_x,lm_2_y,lm_2_z,...,head_tilt,head_stability_label,shoulder_width,posture_openness_label,body_stability_label,body_confidence_label,emotional_state_label,emotional_confidence_label,overall_confidence_label,engagement_label
0,V1,0.395964,0.320213,-0.304125,0.399935,0.291850,-0.286200,0.403436,0.291100,-0.286258,...,0.028363,Stable Head,0.119033,Closed Posture,Stable Body,Moderate Body Confidence,Aggressive / Defensive,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
1,V2,0.383475,0.155170,-0.150292,0.384259,0.143362,-0.125967,0.387558,0.143213,-0.126137,...,0.011808,Stable Head,0.113550,Closed Posture,Stable Body,Moderate Body Confidence,Anxious / Nervous,Emotionally Insecure,Moderately Confident Speaker,Highly Engaged
2,V3,0.384402,0.286855,-0.410269,0.385219,0.256718,-0.369905,0.389300,0.257127,-0.370063,...,0.030137,Stable Head,0.212682,Open Posture,Stable Body,High Body Confidence,Neutral / Controlled,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
3,V4,0.341753,0.489156,-0.127466,0.337333,0.482715,-0.109281,0.337742,0.482798,-0.109392,...,0.006442,Stable Head,0.049823,Closed Posture,Stable Body,Moderate Body Confidence,Anxious / Nervous,Emotionally Insecure,Moderately Confident Speaker,Highly Engaged
4,V5,0.541009,0.186289,-0.174473,0.527455,0.163063,-0.141196,0.527536,0.162719,-0.141512,...,0.023225,Stable Head,0.074201,Closed Posture,Stable Body,Moderate Body Confidence,Aggressive / Defensive,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,V109,0.284816,0.317117,-0.863272,0.312612,0.291836,-0.809081,0.320804,0.293290,-0.809706,...,0.025281,Stable Head,0.323374,Open Posture,Stable Body,High Body Confidence,Neutral / Controlled,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
109,V110,0.498405,0.336019,-0.476285,0.511188,0.320361,-0.456019,0.516909,0.322599,-0.456092,...,0.015658,Stable Head,0.117101,Closed Posture,Stable Body,Moderate Body Confidence,Anxious / Nervous,Emotionally Insecure,Moderately Confident Speaker,Highly Engaged
110,V111,0.453668,0.276462,-0.051321,0.447577,0.260737,-0.042861,0.446975,0.260576,-0.042959,...,0.015725,Stable Head,0.005324,Closed Posture,Stable Body,Moderate Body Confidence,Anxious / Nervous,Emotionally Insecure,Moderately Confident Speaker,Highly Engaged
111,V112,0.400403,0.328811,-0.348069,0.387171,0.292032,-0.325842,0.388248,0.289955,-0.326018,...,0.036779,Stable Head,0.104581,Closed Posture,Stable Body,Moderate Body Confidence,Neutral / Controlled,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
112,V113,0.527650,0.421003,-0.400042,0.530669,0.402517,-0.365860,0.534967,0.402685,-0.366037,...,0.018486,Stable Head,0.152820,Open Posture,Stable Body,High Body Confidence,Aggressive / Defensive,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged

In [31]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [35]:
final_df.columns

Index(['video_name', 'lm_0_x', 'lm_0_y', 'lm_0_z', 'lm_1_x', 'lm_1_y',
       'lm_1_z', 'lm_2_x', 'lm_2_y', 'lm_2_z',
       ...
       'head_tilt', 'head_stability_label', 'shoulder_width',
       'posture_openness_label', 'body_stability_label',
       'body_confidence_label', 'emotional_state_label',
       'emotional_confidence_label', 'overall_confidence_label',
       'engagement_label'],
      dtype='object', length=124)

In [37]:
final_df.to_excel(
    r"C:\Users\DELL\Downloads\body_fer_dataset_completeDT.xlsx",
    index=False
)

In [1]:
import pandas as pd
complete_df=pd.read_excel("Downloads/Graduation_project/body_fer_dataset_completeDT.xlsx")
complete_df

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\DELL\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\DELL\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\DELL\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\DELL\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\DELL\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\DELL\AppData\Local\Temp\ipykernel_21452\593266927.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 52, in <module>
    from pandas.core import (
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\DELL\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\DELL\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\DELL\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\DELL\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\DELL\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\DELL\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\DELL\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\DELL\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\DELL\AppData\Local\Temp\ipykernel_21452\593266927.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 66, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\masked.py", line 61, in <module>
    from pandas.core import (
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\DELL\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\DELL\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

,video_name,lm_0_x,lm_0_y,lm_0_z,lm_1_x,lm_1_y,lm_1_z,lm_2_x,lm_2_y,lm_2_z,...,head_tilt,head_stability_label,shoulder_width,posture_openness_label,body_stability_label,body_confidence_label,emotional_state_label,emotional_confidence_label,overall_confidence_label,engagement_label
0,V1,0.395964,0.320213,-0.304125,0.399935,0.291850,-0.286200,0.403436,0.291100,-0.286258,...,0.028363,Stable Head,0.119033,Closed Posture,Stable Body,Moderate Body Confidence,Aggressive / Defensive,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
1,V2,0.383475,0.155170,-0.150292,0.384259,0.143362,-0.125967,0.387558,0.143213,-0.126137,...,0.011808,Stable Head,0.113550,Closed Posture,Stable Body,Moderate Body Confidence,Anxious / Nervous,Emotionally Insecure,Moderately Confident Speaker,Highly Engaged
2,V3,0.384402,0.286855,-0.410269,0.385219,0.256718,-0.369905,0.389300,0.257127,-0.370063,...,0.030137,Stable Head,0.212682,Open Posture,Stable Body,High Body Confidence,Neutral / Controlled,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
3,V4,0.341753,0.489156,-0.127466,0.337333,0.482715,-0.109281,0.337742,0.482798,-0.109392,...,0.006442,Stable Head,0.049823,Closed Posture,Stable Body,Moderate Body Confidence,Anxious / Nervous,Emotionally Insecure,Moderately Confident Speaker,Highly Engaged
4,V5,0.541009,0.186289,-0.174473,0.527455,0.163063,-0.141196,0.527536,0.162719,-0.141512,...,0.023225,Stable Head,0.074201,Closed Posture,Stable Body,Moderate Body Confidence,Aggressive / Defensive,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,V109,0.284816,0.317117,-0.863272,0.312612,0.291836,-0.809081,0.320804,0.293290,-0.809706,...,0.025281,Stable Head,0.323374,Open Posture,Stable Body,High Body Confidence,Neutral / Controlled,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
109,V110,0.498405,0.336019,-0.476285,0.511188,0.320361,-0.456019,0.516909,0.322599,-0.456092,...,0.015658,Stable Head,0.117101,Closed Posture,Stable Body,Moderate Body Confidence,Anxious / Nervous,Emotionally Insecure,Moderately Confident Speaker,Highly Engaged
110,V111,0.453668,0.276462,-0.051321,0.447577,0.260737,-0.042861,0.446975,0.260576,-0.042959,...,0.015725,Stable Head,0.005324,Closed Posture,Stable Body,Moderate Body Confidence,Anxious / Nervous,Emotionally Insecure,Moderately Confident Speaker,Highly Engaged
111,V112,0.400403,0.328811,-0.348069,0.387171,0.292032,-0.325842,0.388248,0.289955,-0.326018,...,0.036779,Stable Head,0.104581,Closed Posture,Stable Body,Moderate Body Confidence,Neutral / Controlled,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged
112,V113,0.527650,0.421003,-0.400042,0.530669,0.402517,-0.365860,0.534967,0.402685,-0.366037,...,0.018486,Stable Head,0.152820,Open Posture,Stable Body,High Body Confidence,Aggressive / Defensive,Emotionally Balanced,Moderately Confident Speaker,Highly Engaged

In [3]:
complete_df.columns

Index(['video_name', 'lm_0_x', 'lm_0_y', 'lm_0_z', 'lm_1_x', 'lm_1_y',
       'lm_1_z', 'lm_2_x', 'lm_2_y', 'lm_2_z',
       ...
       'head_tilt', 'head_stability_label', 'shoulder_width',
       'posture_openness_label', 'body_stability_label',
       'body_confidence_label', 'emotional_state_label',
       'emotional_confidence_label', 'overall_confidence_label',
       'engagement_label'],
      dtype='object', length=124)

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [7]:
X_body = [
    "lm_0_y", "lm_1_y",
    "lm_11_x", "lm_12_x",
    "lm_23_z"
]

X_emotion = [
    "happy_mean", "sad_mean", "angry_mean",
    "dominant_happy_percent",
    "dominant_fear_percent",
    "dominant_neutral_percent"
]

X_hybrid = X_body + X_emotion

In [9]:
targets = {
    "head_stability_label": X_body,
    "posture_openness_label": X_body,
    "body_stability_label": X_body,
    "body_confidence_label": X_body,

    "emotional_state_label": X_emotion,
    "emotional_confidence_label": X_emotion,

    "overall_confidence_label": X_hybrid,
    "engagement_label": X_hybrid
}

In [23]:
def random_forest_accuracy(df, X_cols, y_col):
    X = df[X_cols]
    y = df[y_col]

    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_encoded, test_size=0.2, random_state=42
    )

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("rf", RandomForestClassifier(
            n_estimators=200,
            max_depth=None,
            random_state=42,
            class_weight="balanced"
        ))
    ])

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    return acc

In [25]:
accuracies = []

for target, X_cols in targets.items():
    acc = random_forest_accuracy(complete_df, X_cols, target)
    accuracies.append(acc)
overall_accuracy = np.mean(accuracies)
print("Random_Forest Accuracy:", round(overall_accuracy, 3))

Random_Forest Accuracy: 0.897

In [27]:
from sklearn.tree import DecisionTreeClassifier
def decision_tree_accuracy(df, X_cols, y_col):
    X = df[X_cols]
    y = df[y_col]

    # Encode Y (labels نصية → أرقام)
    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y_encoded,
        test_size=0.2,
        random_state=42
    )

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("dt", DecisionTreeClassifier(
            max_depth=6,
            min_samples_split=5,
            random_state=42
        ))
    ])

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    return acc

In [33]:
accuracies = []

for target in targets:
    acc = decision_tree_accuracy(complete_df, X_cols, target)
    accuracies.append(acc)

overall_accuracy = np.mean(accuracies)

print(" DecisionTree Accuracy:", round(overall_accuracy, 3))

 DecisionTree Accuracy: 0.918

In [50]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def train_xgboost_model(df, X_cols, y_col):

    X = df[X_cols]
    y = df[y_col]

    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y_encoded,
        test_size=0.2,
        random_state=42
    )

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("xgb", XGBClassifier(
            n_estimators=200,
            max_depth=4,
            learning_rate=0.1,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric="mlogloss",
            random_state=42
        ))
    ])

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    return model, le, acc

In [52]:
accuracies = []

for target, X_cols in targets.items():
    acc = xgboost_accuracy(complete_df, X_cols, target)
    accuracies.append(acc)

overall_accuracy = np.mean(accuracies)

print(" XGBoost Overall Accuracy:", round(overall_accuracy, 3))

 XGBoost Overall Accuracy: 0.929

In [55]:
all_models = {}

for target, X_cols in targets.items():
    model, encoder, acc = train_xgboost_model(complete_df, X_cols, target)
    all_models[target] = {
        "model": model,
        "encoder": encoder
    }

joblib.dump(all_models, "all_xgb_models.pkl")

['all_xgb_models.pkl']

In [108]:
models= joblib.load("all_xgb_models.pkl")

In [114]:
import cv2
import numpy as np
import pandas as pd
from xgboost import XGBClassifier


X_body = [
    "lm_0_y", "lm_1_y",
    "lm_11_x", "lm_12_x",
    "lm_23_z"
]

X_emotion = [
    "happy_mean", "sad_mean", "angry_mean",
    "dominant_happy_percent",
    "dominant_fear_percent",
    "dominant_neutral_percent"
]

X_hybrid = X_body + X_emotion


# ----------------------------------
# 3️⃣ Main Prediction Function
# ----------------------------------

def predict_video(video_path):

    cap = cv2.VideoCapture(video_path)

    body_data = []
    emotion_data = []

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # -------------------------
        # Dummy body features
        # -------------------------
        body_features = {
            "lm_0_y": np.random.rand(),
            "lm_1_y": np.random.rand(),
            "lm_11_x": np.random.rand(),
            "lm_12_x": np.random.rand(),
            "lm_23_z": np.random.rand()
        }
        body_data.append(body_features)

        # -------------------------
        # Dummy emotion features
        # -------------------------
        emotion_features = {
            "happy_mean": np.random.rand(),
            "sad_mean": np.random.rand(),
            "angry_mean": np.random.rand(),
            "dominant_happy_percent": np.random.rand(),
            "dominant_fear_percent": np.random.rand(),
            "dominant_neutral_percent": np.random.rand()
        }
        emotion_data.append(emotion_features)

    cap.release()

    if len(body_data) == 0 or len(emotion_data) == 0:
        print("Video empty or features missing!")
        return {}

    body_df = pd.DataFrame(body_data)
    emotion_df = pd.DataFrame(emotion_data)

    body_mean = body_df.mean().to_dict()
    emotion_mean = emotion_df.mean().to_dict()

    final_features = {**body_mean, **emotion_mean}
    final_df = pd.DataFrame([final_features])

    # ✅ تأكدي كل الأعمدة موجودة
    for col in X_hybrid:
        if col not in final_df.columns:
            final_df[col] = 0.0

    predictions = {}

    for label, model_data in models.items():
        model = model_data["model"]
        encoder = model_data["encoder"]

        if label in ["head_stability_label",
                     "posture_openness_label",
                     "body_stability_label",
                     "body_confidence_label"]:
            X_input = final_df[X_body]

        elif label in ["emotional_state_label",
                       "emotional_confidence_label"]:
            X_input = final_df[X_emotion]

        else:
            X_input = final_df[X_hybrid]

        pred_encoded = model.predict(X_input)[0]
        pred_label = encoder.inverse_transform([pred_encoded])[0]
        predictions[label] = pred_label

    return predictions

In [118]:
result = predict_video("Downloads/Sozy pleading.mp4")

print(result)

{'head_stability_label': 'Stable Head', 'posture_openness_label': 'Closed Posture', 'body_stability_label': 'Stable Body', 'body_confidence_label': 'Moderate Body Confidence', 'emotional_state_label': 'Anxious / Nervous', 'emotional_confidence_label': 'Emotionally Insecure', 'overall_confidence_label': 'Moderately Confident Speaker', 'engagement_label': 'Highly Engaged'}